import type { SoundCue, SoundService } from '@chromawave/domain';
import { createAudioPlayer, setAudioModeAsync, type AudioPlayer } from 'expo-audio';

/**
 * BUILD KIT · 05 · SOUND · "opt-in, off by default".
 *
 * The four cues are generated by `@chromawave/brand-assets` (synthesised, so no
 * licence) and bundled as CAF — the format the kit asks for — transcoded from the
 * WAV masters with macOS's `afconvert`. OGG is not produced; see
 * `docs/24-build-kit.md`.
 */
const FILES: Record<SoundCue, number> = {
  shutter: require('../../assets/brand/sound/shutter.caf'),
  extractDone: require('../../assets/brand/sound/extract-done.caf'),
  save: require('../../assets/brand/sound/save.caf'),
  error: require('../../assets/brand/sound/error.caf'),
};

export class ExpoSoundService implements SoundService {
  private players = new Map<SoundCue, AudioPlayer>();
  private configured = false;

  constructor(private soundEnabled = false) {}

  get enabled(): boolean {
    return this.soundEnabled;
  }

  setEnabled(enabled: boolean): void {
    this.soundEnabled = enabled;
  }

  async play(cue: SoundCue): Promise<void> {
    if (!this.soundEnabled) return;
    try {
      await this.configure();
      const player = this.players.get(cue) ?? createAudioPlayer(FILES[cue]);
      this.players.set(cue, player);
      player.seekTo(0);
      player.play();
    } catch {
      // A cue that cannot play is never worth interrupting the user for.
    }
  }

  /**
   * The kit: "Never plays if the ringer is silenced or audio is already routed to
   * media." `playsInSilentMode: false` gives the first, and not claiming the
   * audio session (`shouldRouteThroughEarpiece` off, no interruption mode) means
   * an active media session keeps the route.
   */
  private async configure(): Promise<void> {
    if (this.configured) return;
    await setAudioModeAsync({
      playsInSilentMode: false,
      shouldPlayInBackground: false,
      interruptionMode: 'mixWithOthers',
    });
    this.configured = true;
  }
}
