import { NEUTRAL_GRADE, type Grade } from './grading';

/**
 * The look library.
 *
 * Separate from `grading.ts` on purpose: that module defines what a grade *is*
 * and how one is derived from a photograph, and thirty sets of numbers sitting
 * on top of it would bury the argument. This module is the catalogue.
 *
 * Every look is the same `Grade` an automatic read produces. That is the whole
 * design: choosing a look and letting the photograph choose for itself yield the
 * same kind of object, so the picker, the dial, the storage and the renderer
 * never learn the difference.
 *
 * Names say what a look does rather than which film it nods at — partly because
 * a stock name is a trademark, and partly because "warm skin, lifted shadows" is
 * more use to someone choosing than a word they may never have shot.
 *
 * **Collections are indexed two ways, and that is deliberate.** The first five
 * name a *process* — negative, slide, monochrome, after dark, early digital —
 * which is what someone who already shoots film comes looking for. The ten after
 * them name a *subject* — portrait, landscape, street, seasons — which is what
 * everyone else comes looking for, because they know what they photographed and
 * not what stock it would have been. Both rails lead to the same kind of object,
 * so nothing downstream has to know which door a look came through.
 */

export const lookCollectionIds = [
  'negative',
  'slide',
  'monochrome',
  'after-dark',
  'early-digital',
  'cinema',
  'portrait',
  'landscape',
  'street',
  'pastel',
  'editorial',
  'seasons',
  'travel',
  'still-life',
  'darkroom',
] as const;
export type LookCollectionId = (typeof lookCollectionIds)[number];

export type Look = Readonly<{
  id: string;
  /** What it does, in the app's own words. Never a film's name. */
  name: string;
  collection: LookCollectionId;
  /**
   * One look per collection is free.
   *
   * A wall of locked chips tells someone the app is not for them. One working
   * look per collection tells them what the collection *is*, which is the thing
   * worth paying to unlock.
   */
  free: boolean;
  grade: Grade;
}>;

export const LOOKS: readonly Look[] = [
  {
    id: 'portra',
    name: 'Warm skin',
    collection: 'negative',
    free: true,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: 0.06,
      contrast: -0.18,
      lift: 0.08,
      saturation: -0.12,
      temperature: 0.2,
      shadowTint: { hue: 30, strength: 0.14 },
      highlightTint: { hue: 45, strength: 0.12 },
      grain: 0.18,
    },
  },
  {
    id: 'polaroid',
    name: 'Instant',
    collection: 'negative',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: 0.1,
      contrast: -0.24,
      lift: 0.14,
      saturation: -0.2,
      temperature: 0.1,
      tint: 0.08,
      shadowTint: { hue: 190, strength: 0.2 },
      highlightTint: { hue: 55, strength: 0.18 },
      vignette: 0.18,
      grain: 0.2,
    },
  },
  {
    id: 'faded-print',
    name: 'Faded print',
    collection: 'negative',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      contrast: -0.22,
      lift: 0.12,
      saturation: -0.3,
      temperature: -0.05,
      shadowTint: { hue: 300, strength: 0.18 },
      grain: 0.14,
    },
  },
  {
    id: 'golden-hour',
    name: 'Golden hour',
    collection: 'negative',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: 0.12,
      contrast: 0.05,
      lift: 0.05,
      saturation: 0.05,
      temperature: 0.3,
      shadowTint: { hue: 35, strength: 0.2 },
      highlightTint: { hue: 60, strength: 0.22 },
      vignette: 0.1,
      grain: 0.2,
    },
  },
  {
    id: 'overcast',
    name: 'Overcast',
    collection: 'negative',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: -0.04,
      contrast: -0.14,
      lift: 0.06,
      saturation: -0.22,
      temperature: -0.2,
      shadowTint: { hue: 220, strength: 0.2 },
      grain: 0.16,
    },
  },
  {
    id: 'pushed',
    name: 'Pushed two stops',
    collection: 'negative',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: 0.05,
      contrast: 0.26,
      lift: 0.05,
      saturation: -0.18,
      temperature: 0.08,
      shadowTint: { hue: 25, strength: 0.16 },
      vignette: 0.24,
      grain: 0.4,
    },
  },
  {
    id: 'ektachrome',
    name: 'Clean slide',
    collection: 'slide',
    free: true,
    grade: {
      ...NEUTRAL_GRADE,
      contrast: 0.22,
      saturation: 0.08,
      temperature: -0.08,
      lift: -0.02,
      shadowTint: { hue: 225, strength: 0.16 },
      grain: 0.08,
    },
  },
  {
    id: 'velvia',
    name: 'Saturated landscape',
    collection: 'slide',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      contrast: 0.32,
      saturation: 0.28,
      lift: -0.05,
      temperature: 0.06,
      shadowTint: { hue: 240, strength: 0.12 },
      vignette: 0.22,
      grain: 0.05,
    },
  },
  {
    id: 'deep-chrome',
    name: 'Deep chrome',
    collection: 'slide',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      contrast: 0.3,
      saturation: 0.3,
      lift: -0.06,
      temperature: -0.14,
      shadowTint: { hue: 230, strength: 0.24 },
      vignette: 0.26,
    },
  },
  {
    id: 'sunlit-chrome',
    name: 'Sunlit chrome',
    collection: 'slide',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: 0.1,
      contrast: 0.24,
      saturation: 0.22,
      temperature: 0.22,
      lift: -0.04,
      highlightTint: { hue: 55, strength: 0.2 },
      vignette: 0.2,
    },
  },
  {
    id: 'cross-process',
    name: 'Cross process',
    collection: 'slide',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      contrast: 0.28,
      saturation: 0.18,
      temperature: -0.1,
      tint: 0.2,
      lift: 0.1,
      shadowTint: { hue: 175, strength: 0.35 },
      highlightTint: { hue: 330, strength: 0.3 },
      vignette: 0.12,
      grain: 0.1,
    },
  },
  {
    id: 'muted-chrome',
    name: 'Muted chrome',
    collection: 'slide',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      contrast: 0.2,
      saturation: -0.2,
      temperature: 0.05,
      lift: 0.04,
      shadowTint: { hue: 120, strength: 0.18 },
      vignette: 0.1,
      grain: 0.06,
    },
  },
  {
    id: 'tri-x',
    name: 'Black and grain',
    collection: 'monochrome',
    free: true,
    grade: {
      ...NEUTRAL_GRADE,
      contrast: 0.3,
      saturation: -1,
      lift: 0.06,
      vignette: 0.2,
      grain: 0.4,
    },
  },
  {
    id: 'soft-mono',
    name: 'Soft mono',
    collection: 'monochrome',
    free: false,
    grade: { ...NEUTRAL_GRADE, contrast: -0.2, saturation: -1, lift: 0.1, grain: 0.08 },
  },
  {
    id: 'hard-mono',
    name: 'Hard mono',
    collection: 'monochrome',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      contrast: 0.4,
      saturation: -1,
      lift: -0.06,
      vignette: 0.12,
      grain: 0.06,
    },
  },
  {
    /**
     * Warmth from the split tone, not from the white balance.
     *
     * Saturation runs after white balance and throws it away, so `temperature`
     * on a monochrome look is a sentence `describeGrade` reads out and the
     * renderer never honours. The split tone runs last, so it survives.
     */
    id: 'toned-warm',
    name: 'Warm tone',
    collection: 'monochrome',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      contrast: 0.1,
      saturation: -1,
      lift: 0.08,
      shadowTint: { hue: 30, strength: 0.34 },
      highlightTint: { hue: 55, strength: 0.24 },
      grain: 0.22,
    },
  },
  {
    id: 'toned-cool',
    name: 'Cool tone',
    collection: 'monochrome',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      contrast: 0.26,
      saturation: -1,
      lift: 0.04,
      shadowTint: { hue: 240, strength: 0.3 },
      vignette: 0.22,
      grain: 0.16,
    },
  },
  {
    id: 'newsprint',
    name: 'Newsprint',
    collection: 'monochrome',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: 0.14,
      contrast: 0.18,
      saturation: -1,
      lift: 0.12,
      grain: 0.5,
    },
  },
  {
    id: 'cinestill',
    name: 'Tungsten night',
    collection: 'after-dark',
    free: true,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: -0.08,
      contrast: 0.16,
      lift: 0.1,
      temperature: -0.24,
      saturation: 0.06,
      shadowTint: { hue: 250, strength: 0.28 },
      highlightTint: { hue: 15, strength: 0.22 },
      vignette: 0.24,
      grain: 0.26,
    },
  },
  {
    id: 'neon',
    name: 'Neon',
    collection: 'after-dark',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: -0.06,
      contrast: 0.24,
      lift: 0.08,
      saturation: 0.24,
      temperature: -0.16,
      shadowTint: { hue: 290, strength: 0.3 },
      highlightTint: { hue: 180, strength: 0.24 },
      vignette: 0.28,
      grain: 0.12,
    },
  },
  {
    id: 'sodium',
    name: 'Street light',
    collection: 'after-dark',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: -0.1,
      contrast: 0.2,
      lift: 0.1,
      saturation: -0.1,
      temperature: 0.28,
      shadowTint: { hue: 35, strength: 0.28 },
      highlightTint: { hue: 50, strength: 0.26 },
      vignette: 0.26,
      grain: 0.3,
    },
  },
  {
    id: 'blue-hour',
    name: 'Blue hour',
    collection: 'after-dark',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: -0.05,
      contrast: -0.14,
      lift: 0.1,
      saturation: -0.12,
      temperature: -0.3,
      shadowTint: { hue: 235, strength: 0.3 },
      highlightTint: { hue: 280, strength: 0.18 },
      vignette: 0.14,
      grain: 0.18,
    },
  },
  {
    id: 'available-dark',
    name: 'Available darkness',
    collection: 'after-dark',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: -0.12,
      contrast: 0.3,
      lift: -0.04,
      saturation: -0.34,
      temperature: -0.08,
      shadowTint: { hue: 245, strength: 0.2 },
      vignette: 0.3,
      grain: 0.45,
    },
  },
  {
    id: 'interior',
    name: 'Interior lamp',
    collection: 'after-dark',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: 0.06,
      contrast: -0.16,
      lift: 0.12,
      saturation: -0.08,
      temperature: 0.24,
      shadowTint: { hue: 10, strength: 0.2 },
      highlightTint: { hue: 40, strength: 0.2 },
      vignette: 0.1,
      grain: 0.14,
    },
  },

  /**
   * Early digital dates a photograph rather than warming it.
   *
   * The other four collections are film, and film is what people reach for when
   * they want a picture to look *better*. This one is for wanting it to look
   * like it was taken at a particular time — green casts, blown flash, crushed
   * shadows, the artefacts of a sensor that was not very good yet.
   */
  {
    id: 'camcorder',
    name: 'Camcorder',
    collection: 'early-digital',
    free: true,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: 0.1,
      contrast: -0.16,
      saturation: -0.14,
      temperature: -0.06,
      tint: -0.24,
      shadowTint: { hue: 110, strength: 0.26 },
      highlightTint: { hue: 95, strength: 0.2 },
      vignette: 0.16,
      grain: 0.1,
    },
  },
  {
    id: 'tape',
    name: 'Tape',
    collection: 'early-digital',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: 0.04,
      contrast: -0.18,
      lift: 0.14,
      saturation: 0.12,
      temperature: 0.06,
      tint: 0.22,
      shadowTint: { hue: 325, strength: 0.28 },
      highlightTint: { hue: 185, strength: 0.2 },
      vignette: 0.2,
      grain: 0.34,
    },
  },
  {
    id: 'direct-flash',
    name: 'Direct flash',
    collection: 'early-digital',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: 0.16,
      contrast: 0.28,
      lift: -0.05,
      saturation: -0.18,
      temperature: -0.14,
      shadowTint: { hue: 170, strength: 0.18 },
      vignette: 0.24,
      grain: 0.08,
    },
  },
  {
    id: 'low-res',
    name: 'Low resolution',
    collection: 'early-digital',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: -0.06,
      contrast: 0.22,
      lift: -0.04,
      saturation: -0.26,
      temperature: 0.1,
      shadowTint: { hue: 295, strength: 0.2 },
      highlightTint: { hue: 65, strength: 0.18 },
      grain: 0.38,
    },
  },
  {
    id: 'screen-glow',
    name: 'Screen glow',
    collection: 'early-digital',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: 0.08,
      contrast: -0.2,
      lift: 0.16,
      saturation: 0.14,
      temperature: -0.22,
      shadowTint: { hue: 215, strength: 0.24 },
      grain: 0.2,
    },
  },
  {
    id: 'early-web',
    name: 'Early web',
    collection: 'early-digital',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      contrast: 0.34,
      saturation: 0.34,
      temperature: 0.14,
      highlightTint: { hue: 45, strength: 0.2 },
      vignette: 0.22,
    },
  },

  /**
   * Cinema grades the frame rather than the film.
   *
   * The separation is the whole collection: a colourist working on a picture
   * pushes shadow and highlight in opposite directions on the hue circle, which
   * is what the split tone was built for and what no single white balance can
   * do. Every entry here is a hue pair first and a level second.
   */
  {
    id: 'teal-orange',
    name: 'Teal and orange',
    collection: 'cinema',
    free: true,
    grade: {
      ...NEUTRAL_GRADE,
      contrast: 0.24,
      saturation: 0.08,
      temperature: 0.1,
      lift: -0.04,
      shadowTint: { hue: 180, strength: 0.3 },
      highlightTint: { hue: 30, strength: 0.26 },
      vignette: 0.22,
      grain: 0.06,
    },
  },
  {
    id: 'bleach-bypass',
    name: 'Bleach bypass',
    collection: 'cinema',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: 0.06,
      contrast: 0.36,
      saturation: -0.4,
      lift: -0.05,
      shadowTint: { hue: 230, strength: 0.16 },
      vignette: 0.18,
      grain: 0.14,
    },
  },
  {
    id: 'day-for-night',
    name: 'Day for night',
    collection: 'cinema',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: -0.14,
      contrast: 0.2,
      lift: 0.05,
      saturation: -0.2,
      temperature: -0.34,
      shadowTint: { hue: 230, strength: 0.34 },
      highlightTint: { hue: 285, strength: 0.18 },
      vignette: 0.3,
      grain: 0.1,
    },
  },
  {
    id: 'anamorphic',
    name: 'Anamorphic',
    collection: 'cinema',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: 0.08,
      contrast: 0.18,
      lift: 0.06,
      temperature: -0.05,
      shadowTint: { hue: 235, strength: 0.2 },
      highlightTint: { hue: 185, strength: 0.28 },
      vignette: 0.24,
      grain: 0.08,
    },
  },
  {
    id: 'cold-thriller',
    name: 'Cold thriller',
    collection: 'cinema',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      contrast: 0.3,
      lift: 0.04,
      saturation: -0.3,
      temperature: -0.2,
      shadowTint: { hue: 175, strength: 0.26 },
      vignette: 0.26,
      grain: 0.12,
    },
  },
  {
    id: 'warm-romance',
    name: 'Warm romance',
    collection: 'cinema',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: 0.1,
      contrast: -0.16,
      lift: 0.08,
      saturation: 0.02,
      temperature: 0.24,
      shadowTint: { hue: 12, strength: 0.16 },
      highlightTint: { hue: 35, strength: 0.24 },
      vignette: 0.14,
      grain: 0.12,
    },
  },
  {
    id: 'epic-dusk',
    name: 'Epic dusk',
    collection: 'cinema',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: -0.06,
      contrast: 0.26,
      lift: -0.04,
      saturation: 0.14,
      temperature: 0.16,
      shadowTint: { hue: 290, strength: 0.24 },
      highlightTint: { hue: 58, strength: 0.24 },
      vignette: 0.28,
      grain: 0.08,
    },
  },
  {
    id: 'cold-future',
    name: 'Cold future',
    collection: 'cinema',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: -0.05,
      contrast: 0.22,
      lift: 0.05,
      saturation: 0.12,
      temperature: -0.28,
      shadowTint: { hue: 190, strength: 0.3 },
      highlightTint: { hue: 215, strength: 0.22 },
      vignette: 0.2,
      grain: 0.1,
    },
  },

  /**
   * Portrait is the collection with the least room to move.
   *
   * Skin sits in a narrow band of hues, and a grade that misses it reads as an
   * illness rather than as a look. So the levels here are small, the shadow
   * carries most of the colour, and nothing pushes saturation hard enough to
   * turn a face orange.
   */
  {
    id: 'clean-skin',
    name: 'Clean skin',
    collection: 'portrait',
    free: true,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: 0.06,
      contrast: -0.14,
      lift: 0.05,
      saturation: -0.05,
      temperature: 0.14,
      shadowTint: { hue: 180, strength: 0.16 },
      highlightTint: { hue: 40, strength: 0.18 },
      grain: 0.08,
    },
  },
  {
    id: 'soft-beauty',
    name: 'Soft beauty',
    collection: 'portrait',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: 0.14,
      contrast: -0.22,
      lift: 0.12,
      saturation: -0.16,
      temperature: 0.06,
      shadowTint: { hue: 300, strength: 0.18 },
      highlightTint: { hue: 8, strength: 0.2 },
      grain: 0.1,
    },
  },
  {
    id: 'studio-strobe',
    name: 'Studio strobe',
    collection: 'portrait',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: 0.1,
      contrast: 0.2,
      lift: -0.05,
      shadowTint: { hue: 225, strength: 0.18 },
      vignette: 0.1,
      grain: 0.04,
    },
  },
  {
    id: 'window-light',
    name: 'Window light',
    collection: 'portrait',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: 0.08,
      contrast: -0.14,
      lift: 0.09,
      saturation: -0.08,
      temperature: -0.14,
      shadowTint: { hue: 240, strength: 0.22 },
      highlightTint: { hue: 62, strength: 0.16 },
      grain: 0.12,
    },
  },
  {
    id: 'honey-skin',
    name: 'Honey skin',
    collection: 'portrait',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: 0.04,
      contrast: 0.06,
      lift: 0.06,
      saturation: 0.12,
      temperature: 0.3,
      shadowTint: { hue: 32, strength: 0.24 },
      highlightTint: { hue: 55, strength: 0.2 },
      grain: 0.14,
    },
  },
  {
    id: 'matte-portrait',
    name: 'Matte portrait',
    collection: 'portrait',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      contrast: -0.2,
      lift: 0.14,
      saturation: -0.22,
      temperature: 0.08,
      shadowTint: { hue: 130, strength: 0.2 },
      highlightTint: { hue: 42, strength: 0.16 },
      grain: 0.2,
    },
  },
  {
    id: 'low-key',
    name: 'Low key',
    collection: 'portrait',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: -0.16,
      contrast: 0.3,
      lift: -0.04,
      saturation: -0.18,
      temperature: 0.12,
      shadowTint: { hue: 14, strength: 0.2 },
      vignette: 0.34,
      grain: 0.12,
    },
  },
  {
    id: 'high-key',
    name: 'High key',
    collection: 'portrait',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: 0.2,
      contrast: -0.24,
      lift: 0.16,
      saturation: -0.2,
      temperature: -0.06,
      highlightTint: { hue: 178, strength: 0.18 },
      grain: 0.06,
    },
  },

  /**
   * Landscape is the one collection where saturation is allowed to be the point.
   *
   * Nothing in a wide frame has a memory colour as unforgiving as skin, so these
   * push further than portrait ever could — and the vignette does real work,
   * because a landscape usually has nothing at its corners worth keeping.
   */
  {
    id: 'open-air',
    name: 'Open air',
    collection: 'landscape',
    free: true,
    grade: {
      ...NEUTRAL_GRADE,
      contrast: 0.18,
      saturation: 0.14,
      temperature: -0.06,
      shadowTint: { hue: 220, strength: 0.2 },
      highlightTint: { hue: 58, strength: 0.18 },
      vignette: 0.14,
    },
  },
  {
    id: 'deep-forest',
    name: 'Deep forest',
    collection: 'landscape',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: -0.04,
      contrast: 0.16,
      lift: 0.05,
      saturation: 0.1,
      temperature: -0.1,
      shadowTint: { hue: 125, strength: 0.28 },
      highlightTint: { hue: 70, strength: 0.2 },
      vignette: 0.22,
      grain: 0.08,
    },
  },
  {
    id: 'desert',
    name: 'Desert',
    collection: 'landscape',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: 0.1,
      contrast: 0.16,
      lift: 0.04,
      saturation: -0.16,
      temperature: 0.28,
      shadowTint: { hue: 28, strength: 0.22 },
      highlightTint: { hue: 65, strength: 0.24 },
      vignette: 0.16,
      grain: 0.1,
    },
  },
  {
    id: 'alpine',
    name: 'Alpine',
    collection: 'landscape',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: 0.12,
      contrast: 0.24,
      lift: -0.04,
      saturation: 0.08,
      temperature: -0.22,
      shadowTint: { hue: 235, strength: 0.26 },
      vignette: 0.18,
      grain: 0.05,
    },
  },
  {
    id: 'coast',
    name: 'Coast',
    collection: 'landscape',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: 0.06,
      contrast: -0.14,
      lift: 0.06,
      saturation: 0.12,
      temperature: -0.16,
      shadowTint: { hue: 185, strength: 0.26 },
      highlightTint: { hue: 210, strength: 0.16 },
      grain: 0.08,
    },
  },
  {
    id: 'mist',
    name: 'Mist',
    collection: 'landscape',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: 0.08,
      contrast: -0.24,
      lift: 0.15,
      saturation: -0.3,
      temperature: -0.08,
      shadowTint: { hue: 195, strength: 0.2 },
      grain: 0.16,
    },
  },
  {
    id: 'heather',
    name: 'Heather',
    collection: 'landscape',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      contrast: 0.1,
      lift: 0.05,
      temperature: -0.14,
      shadowTint: { hue: 295, strength: 0.26 },
      highlightTint: { hue: 330, strength: 0.2 },
      vignette: 0.22,
      grain: 0.14,
    },
  },
  {
    id: 'wide-vista',
    name: 'Wide vista',
    collection: 'landscape',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: -0.04,
      contrast: 0.3,
      lift: 0.04,
      saturation: 0.24,
      temperature: 0.14,
      shadowTint: { hue: 170, strength: 0.2 },
      highlightTint: { hue: 38, strength: 0.22 },
      vignette: 0.26,
      grain: 0.04,
    },
  },

  /**
   * Street carries grain the way the others carry vignette.
   *
   * These are grades for photographs taken at whatever the light happened to be,
   * usually fast and usually pushed, so the honest move is to let the noise read
   * as texture rather than to pretend it away.
   */
  {
    id: 'documentary',
    name: 'Documentary',
    collection: 'street',
    free: true,
    grade: {
      ...NEUTRAL_GRADE,
      contrast: 0.2,
      lift: 0.06,
      saturation: -0.2,
      temperature: 0.04,
      shadowTint: { hue: 35, strength: 0.16 },
      vignette: 0.14,
      grain: 0.28,
    },
  },
  {
    id: 'rush-hour',
    name: 'Rush hour',
    collection: 'street',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: -0.06,
      contrast: 0.28,
      lift: 0.06,
      saturation: 0.16,
      temperature: 0.18,
      shadowTint: { hue: 245, strength: 0.22 },
      highlightTint: { hue: 52, strength: 0.22 },
      vignette: 0.24,
      grain: 0.2,
    },
  },
  {
    id: 'subway',
    name: 'Subway',
    collection: 'street',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: -0.12,
      contrast: 0.24,
      lift: 0.08,
      saturation: -0.24,
      temperature: -0.06,
      shadowTint: { hue: 115, strength: 0.24 },
      highlightTint: { hue: 175, strength: 0.18 },
      vignette: 0.22,
      grain: 0.34,
    },
  },
  {
    id: 'pavement',
    name: 'Pavement',
    collection: 'street',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      contrast: 0.34,
      lift: -0.05,
      saturation: -0.36,
      temperature: -0.05,
      shadowTint: { hue: 250, strength: 0.22 },
      vignette: 0.1,
      grain: 0.24,
    },
  },
  {
    id: 'market',
    name: 'Market',
    collection: 'street',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: 0.06,
      contrast: 0.14,
      lift: 0.05,
      saturation: 0.26,
      temperature: 0.22,
      shadowTint: { hue: 15, strength: 0.22 },
      highlightTint: { hue: 44, strength: 0.2 },
      grain: 0.16,
    },
  },
  {
    id: 'wet-street',
    name: 'Wet street',
    collection: 'street',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: -0.08,
      contrast: 0.2,
      lift: 0.07,
      saturation: 0.1,
      temperature: -0.24,
      shadowTint: { hue: 182, strength: 0.28 },
      highlightTint: { hue: 325, strength: 0.2 },
      vignette: 0.24,
      grain: 0.16,
    },
  },
  {
    id: 'harsh-noon',
    name: 'Harsh noon',
    collection: 'street',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: 0.12,
      contrast: 0.32,
      lift: -0.06,
      saturation: -0.18,
      temperature: 0.14,
      shadowTint: { hue: 285, strength: 0.18 },
      vignette: 0.12,
      grain: 0.1,
    },
  },
  {
    id: 'quiet-lane',
    name: 'Quiet lane',
    collection: 'street',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      contrast: -0.16,
      lift: 0.1,
      saturation: -0.16,
      temperature: 0.1,
      shadowTint: { hue: 68, strength: 0.2 },
      highlightTint: { hue: 6, strength: 0.16 },
      grain: 0.22,
    },
  },

  /**
   * Pastel is lift doing the work, not exposure.
   *
   * Brightening a photograph moves the whole curve and blows the highlights;
   * raising the black point moves only the bottom of it, which is the difference
   * between a washed print and an overexposed one.
   */
  {
    id: 'powder',
    name: 'Powder',
    collection: 'pastel',
    free: true,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: 0.12,
      contrast: -0.2,
      lift: 0.14,
      saturation: -0.24,
      temperature: 0.06,
      shadowTint: { hue: 215, strength: 0.24 },
      highlightTint: { hue: 335, strength: 0.18 },
      grain: 0.06,
    },
  },
  {
    id: 'blush',
    name: 'Blush',
    collection: 'pastel',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: 0.1,
      contrast: -0.18,
      lift: 0.13,
      saturation: -0.1,
      temperature: 0.16,
      shadowTint: { hue: 330, strength: 0.24 },
      highlightTint: { hue: 10, strength: 0.18 },
      grain: 0.08,
    },
  },
  {
    id: 'mint',
    name: 'Mint',
    collection: 'pastel',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: 0.08,
      contrast: -0.16,
      lift: 0.12,
      saturation: -0.2,
      temperature: -0.1,
      shadowTint: { hue: 145, strength: 0.26 },
      highlightTint: { hue: 190, strength: 0.16 },
      grain: 0.05,
    },
  },
  {
    id: 'lavender',
    name: 'Lavender',
    collection: 'pastel',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      contrast: -0.2,
      lift: 0.14,
      saturation: -0.12,
      temperature: -0.14,
      shadowTint: { hue: 292, strength: 0.28 },
      highlightTint: { hue: 225, strength: 0.18 },
      grain: 0.1,
    },
  },
  {
    id: 'peach',
    name: 'Peach',
    collection: 'pastel',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: 0.14,
      contrast: -0.14,
      lift: 0.1,
      saturation: 0.1,
      temperature: 0.2,
      shadowTint: { hue: 26, strength: 0.2 },
      highlightTint: { hue: 56, strength: 0.22 },
      grain: 0.06,
    },
  },
  {
    id: 'oat',
    name: 'Oat',
    collection: 'pastel',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      contrast: -0.14,
      lift: 0.12,
      saturation: -0.26,
      temperature: 0.12,
      shadowTint: { hue: 72, strength: 0.22 },
      highlightTint: { hue: 46, strength: 0.2 },
      grain: 0.14,
    },
  },
  {
    id: 'sky-wash',
    name: 'Sky wash',
    collection: 'pastel',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: 0.16,
      contrast: -0.22,
      lift: 0.15,
      saturation: -0.05,
      temperature: -0.2,
      shadowTint: { hue: 172, strength: 0.22 },
      highlightTint: { hue: 300, strength: 0.16 },
      grain: 0.04,
    },
  },
  {
    id: 'rose-grey',
    name: 'Rose grey',
    collection: 'pastel',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      contrast: -0.16,
      lift: 0.11,
      saturation: -0.3,
      shadowTint: { hue: 355, strength: 0.2 },
      highlightTint: { hue: 305, strength: 0.18 },
      grain: 0.18,
    },
  },

  /**
   * Editorial crushes the black point, and that is the whole family resemblance.
   *
   * A magazine page is printed on paper that cannot hold a lifted shadow, so the
   * house style everywhere from fashion to reportage runs the opposite way to
   * film: contrast up, blacks down, colour held on a short leash.
   */
  {
    id: 'magazine',
    name: 'Magazine',
    collection: 'editorial',
    free: true,
    grade: {
      ...NEUTRAL_GRADE,
      contrast: 0.26,
      lift: -0.04,
      saturation: -0.1,
      temperature: -0.08,
      shadowTint: { hue: 288, strength: 0.2 },
      highlightTint: { hue: 60, strength: 0.18 },
      vignette: 0.12,
      grain: 0.06,
    },
  },
  {
    id: 'runway',
    name: 'Runway',
    collection: 'editorial',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: 0.1,
      contrast: 0.3,
      lift: -0.05,
      saturation: 0.2,
      temperature: 0.06,
      shadowTint: { hue: 320, strength: 0.22 },
      highlightTint: { hue: 180, strength: 0.2 },
      vignette: 0.2,
      grain: 0.04,
    },
  },
  {
    id: 'campaign',
    name: 'Campaign',
    collection: 'editorial',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      contrast: 0.2,
      lift: 0.06,
      saturation: -0.2,
      temperature: 0.16,
      shadowTint: { hue: 168, strength: 0.24 },
      highlightTint: { hue: 36, strength: 0.24 },
      vignette: 0.16,
      grain: 0.12,
    },
  },
  {
    id: 'cover-story',
    name: 'Cover story',
    collection: 'editorial',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: 0.06,
      contrast: 0.36,
      lift: -0.06,
      saturation: 0.14,
      temperature: -0.16,
      shadowTint: { hue: 240, strength: 0.2 },
      highlightTint: { hue: 338, strength: 0.18 },
      vignette: 0.24,
      grain: 0.06,
    },
  },
  {
    id: 'paper-white',
    name: 'Paper white',
    collection: 'editorial',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: 0.16,
      contrast: 0.22,
      lift: 0.05,
      saturation: -0.34,
      temperature: -0.05,
      highlightTint: { hue: 220, strength: 0.18 },
      grain: 0.08,
    },
  },
  {
    id: 'ink',
    name: 'Ink',
    collection: 'editorial',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: -0.1,
      contrast: 0.32,
      lift: 0.05,
      saturation: -0.28,
      temperature: -0.05,
      shadowTint: { hue: 275, strength: 0.28 },
      highlightTint: { hue: 140, strength: 0.16 },
      vignette: 0.18,
      grain: 0.2,
    },
  },
  {
    id: 'atelier',
    name: 'Atelier',
    collection: 'editorial',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      contrast: -0.14,
      lift: 0.08,
      saturation: -0.05,
      temperature: 0.14,
      shadowTint: { hue: 75, strength: 0.24 },
      highlightTint: { hue: 332, strength: 0.16 },
      vignette: 0.22,
      grain: 0.16,
    },
  },
  {
    id: 'gallery',
    name: 'Gallery',
    collection: 'editorial',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: 0.08,
      contrast: 0.16,
      lift: 0.05,
      shadowTint: { hue: 100, strength: 0.22 },
      highlightTint: { hue: 66, strength: 0.2 },
      vignette: 0.22,
      grain: 0.06,
    },
  },

  /**
   * Seasons is the collection people reach for without knowing any of the words.
   *
   * Nobody has to be told what autumn should look like, which makes these the
   * easiest entries in the library to judge and the hardest to fake: get the
   * shadow hue wrong and the name of the look argues with the photograph.
   */
  {
    id: 'spring',
    name: 'Spring',
    collection: 'seasons',
    free: true,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: 0.08,
      contrast: -0.14,
      lift: 0.07,
      saturation: 0.14,
      temperature: 0.08,
      shadowTint: { hue: 135, strength: 0.22 },
      highlightTint: { hue: 64, strength: 0.18 },
      grain: 0.06,
    },
  },
  {
    id: 'high-summer',
    name: 'High summer',
    collection: 'seasons',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: 0.14,
      contrast: 0.24,
      lift: -0.03,
      saturation: 0.22,
      temperature: 0.24,
      shadowTint: { hue: 232, strength: 0.18 },
      highlightTint: { hue: 54, strength: 0.24 },
      vignette: 0.18,
      grain: 0.05,
    },
  },
  {
    id: 'autumn',
    name: 'Autumn',
    collection: 'seasons',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: -0.04,
      contrast: 0.16,
      lift: 0.05,
      saturation: 0.1,
      temperature: 0.26,
      shadowTint: { hue: 18, strength: 0.26 },
      highlightTint: { hue: 40, strength: 0.22 },
      vignette: 0.18,
      grain: 0.18,
    },
  },
  {
    id: 'late-autumn',
    name: 'Late autumn',
    collection: 'seasons',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: -0.06,
      contrast: -0.14,
      lift: 0.09,
      saturation: -0.28,
      temperature: 0.1,
      shadowTint: { hue: 24, strength: 0.2 },
      highlightTint: { hue: 74, strength: 0.18 },
      vignette: 0.24,
      grain: 0.24,
    },
  },
  {
    id: 'winter',
    name: 'Winter',
    collection: 'seasons',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: 0.1,
      contrast: 0.18,
      lift: 0.06,
      saturation: -0.24,
      temperature: -0.3,
      shadowTint: { hue: 228, strength: 0.28 },
      highlightTint: { hue: 196, strength: 0.18 },
      vignette: 0.14,
      grain: 0.1,
    },
  },
  {
    id: 'first-frost',
    name: 'First frost',
    collection: 'seasons',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: 0.06,
      contrast: 0.2,
      lift: -0.04,
      temperature: -0.18,
      shadowTint: { hue: 188, strength: 0.24 },
      highlightTint: { hue: 296, strength: 0.2 },
      vignette: 0.2,
      grain: 0.08,
    },
  },
  {
    id: 'monsoon',
    name: 'Monsoon',
    collection: 'seasons',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: -0.1,
      contrast: -0.16,
      lift: 0.12,
      saturation: -0.2,
      temperature: -0.14,
      shadowTint: { hue: 150, strength: 0.24 },
      highlightTint: { hue: 205, strength: 0.18 },
      vignette: 0.16,
      grain: 0.22,
    },
  },
  {
    id: 'dry-season',
    name: 'Dry season',
    collection: 'seasons',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: 0.08,
      contrast: 0.1,
      lift: 0.06,
      saturation: -0.16,
      temperature: 0.3,
      shadowTint: { hue: 78, strength: 0.24 },
      highlightTint: { hue: 48, strength: 0.22 },
      vignette: 0.12,
      grain: 0.2,
    },
  },

  /**
   * Travel grades a place rather than a subject.
   *
   * The unifying move is that the shadow takes the hue of the light the place is
   * remembered by — sodium in a souk, sea light on an island — while the
   * highlight stays near the sun, so the frame still reads as somewhere outdoors.
   */
  {
    id: 'postcard',
    name: 'Postcard',
    collection: 'travel',
    free: true,
    grade: {
      ...NEUTRAL_GRADE,
      contrast: 0.22,
      saturation: 0.24,
      temperature: 0.14,
      shadowTint: { hue: 222, strength: 0.22 },
      highlightTint: { hue: 68, strength: 0.24 },
      vignette: 0.16,
      grain: 0.04,
    },
  },
  {
    id: 'island',
    name: 'Island',
    collection: 'travel',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: 0.1,
      contrast: 0.16,
      lift: 0.05,
      saturation: 0.26,
      temperature: -0.14,
      shadowTint: { hue: 192, strength: 0.3 },
      highlightTint: { hue: 50, strength: 0.2 },
      vignette: 0.12,
      grain: 0.05,
    },
  },
  {
    id: 'souk',
    name: 'Souk',
    collection: 'travel',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: -0.06,
      contrast: 0.2,
      lift: 0.08,
      saturation: 0.14,
      temperature: 0.3,
      shadowTint: { hue: 22, strength: 0.28 },
      highlightTint: { hue: 16, strength: 0.2 },
      vignette: 0.26,
      grain: 0.2,
    },
  },
  {
    id: 'northern',
    name: 'Northern',
    collection: 'travel',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: -0.12,
      contrast: 0.18,
      lift: 0.07,
      saturation: 0.1,
      temperature: -0.3,
      shadowTint: { hue: 280, strength: 0.3 },
      highlightTint: { hue: 155, strength: 0.2 },
      vignette: 0.28,
      grain: 0.12,
    },
  },
  {
    id: 'highland',
    name: 'Highland',
    collection: 'travel',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: -0.05,
      contrast: -0.14,
      lift: 0.08,
      saturation: -0.22,
      temperature: -0.16,
      shadowTint: { hue: 110, strength: 0.22 },
      highlightTint: { hue: 76, strength: 0.16 },
      vignette: 0.22,
      grain: 0.2,
    },
  },
  {
    id: 'harbour',
    name: 'Harbour',
    collection: 'travel',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      contrast: 0.24,
      lift: 0.06,
      saturation: -0.05,
      temperature: -0.2,
      shadowTint: { hue: 210, strength: 0.26 },
      highlightTint: { hue: 34, strength: 0.2 },
      vignette: 0.2,
      grain: 0.14,
    },
  },
  {
    id: 'roadside',
    name: 'Roadside',
    collection: 'travel',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: 0.06,
      contrast: 0.16,
      lift: 0.1,
      saturation: -0.2,
      temperature: 0.2,
      shadowTint: { hue: 318, strength: 0.2 },
      highlightTint: { hue: 70, strength: 0.22 },
      vignette: 0.14,
      grain: 0.26,
    },
  },
  {
    id: 'temple',
    name: 'Temple',
    collection: 'travel',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: -0.08,
      contrast: 0.14,
      lift: 0.09,
      saturation: 0.12,
      temperature: 0.28,
      shadowTint: { hue: 4, strength: 0.26 },
      highlightTint: { hue: 58, strength: 0.2 },
      vignette: 0.24,
      grain: 0.16,
    },
  },

  /**
   * Still life is graded for one object under one lamp.
   *
   * A close frame has no sky to anchor the white balance, so these lean on the
   * material instead — what ceramic, linen, brass and paper each do to the light
   * that lands on them — and keep the levels small enough not to plasticise it.
   */
  {
    id: 'table-top',
    name: 'Table top',
    collection: 'still-life',
    free: true,
    grade: {
      ...NEUTRAL_GRADE,
      contrast: 0.14,
      lift: 0.05,
      saturation: -0.05,
      temperature: 0.1,
      shadowTint: { hue: 30, strength: 0.2 },
      highlightTint: { hue: 62, strength: 0.16 },
      vignette: 0.14,
      grain: 0.08,
    },
  },
  {
    id: 'ceramic',
    name: 'Ceramic',
    collection: 'still-life',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: 0.12,
      contrast: -0.16,
      lift: 0.1,
      saturation: -0.18,
      temperature: -0.08,
      shadowTint: { hue: 218, strength: 0.2 },
      highlightTint: { hue: 128, strength: 0.16 },
      grain: 0.06,
    },
  },
  {
    id: 'linen',
    name: 'Linen',
    collection: 'still-life',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: 0.14,
      contrast: -0.2,
      lift: 0.13,
      saturation: -0.24,
      temperature: 0.16,
      shadowTint: { hue: 66, strength: 0.2 },
      highlightTint: { hue: 174, strength: 0.16 },
      grain: 0.12,
    },
  },
  {
    id: 'brass',
    name: 'Brass',
    collection: 'still-life',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      contrast: 0.24,
      lift: -0.04,
      saturation: 0.16,
      temperature: 0.26,
      shadowTint: { hue: 78, strength: 0.22 },
      highlightTint: { hue: 42, strength: 0.24 },
      vignette: 0.24,
      grain: 0.06,
    },
  },
  {
    id: 'glassware',
    name: 'Glassware',
    collection: 'still-life',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: 0.1,
      contrast: 0.2,
      lift: 0.06,
      temperature: -0.2,
      shadowTint: { hue: 198, strength: 0.24 },
      highlightTint: { hue: 208, strength: 0.18 },
      vignette: 0.14,
      grain: 0.04,
    },
  },
  {
    id: 'botanical',
    name: 'Botanical',
    collection: 'still-life',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      contrast: 0.18,
      lift: 0.05,
      saturation: 0.18,
      temperature: -0.06,
      shadowTint: { hue: 118, strength: 0.26 },
      highlightTint: { hue: 328, strength: 0.18 },
      vignette: 0.18,
      grain: 0.08,
    },
  },
  {
    id: 'dark-table',
    name: 'Dark table',
    collection: 'still-life',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: -0.14,
      contrast: 0.28,
      lift: -0.05,
      saturation: -0.12,
      temperature: 0.18,
      shadowTint: { hue: 20, strength: 0.24 },
      highlightTint: { hue: 72, strength: 0.2 },
      vignette: 0.3,
      grain: 0.1,
    },
  },
  {
    id: 'paper',
    name: 'Paper',
    collection: 'still-life',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: 0.08,
      contrast: -0.14,
      lift: 0.12,
      saturation: -0.32,
      shadowTint: { hue: 308, strength: 0.2 },
      highlightTint: { hue: 52, strength: 0.18 },
      vignette: 0.1,
      grain: 0.2,
    },
  },

  /**
   * Darkroom is monochrome with a chemistry.
   *
   * Every entry here strips the colour out and puts a *different* colour back
   * through the split tone, which is exactly what the alternative processes did:
   * iron for cyanotype, silver for selenium, egg and salt for the earliest prints
   * of all. As `toned-warm` already records, the toning has to come from the
   * split tone — white balance runs before saturation and would be discarded.
   */
  {
    id: 'sepia',
    name: 'Sepia',
    collection: 'darkroom',
    free: true,
    grade: {
      ...NEUTRAL_GRADE,
      contrast: 0.14,
      lift: 0.1,
      saturation: -1,
      shadowTint: { hue: 28, strength: 0.36 },
      highlightTint: { hue: 58, strength: 0.3 },
      vignette: 0.24,
      grain: 0.24,
    },
  },
  {
    id: 'cyanotype',
    name: 'Cyanotype',
    collection: 'darkroom',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      contrast: 0.28,
      lift: 0.08,
      saturation: -1,
      shadowTint: { hue: 236, strength: 0.4 },
      highlightTint: { hue: 196, strength: 0.3 },
      vignette: 0.18,
      grain: 0.14,
    },
  },
  {
    id: 'platinum',
    name: 'Platinum',
    collection: 'darkroom',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      contrast: -0.16,
      lift: 0.06,
      saturation: -1,
      shadowTint: { hue: 70, strength: 0.2 },
      highlightTint: { hue: 44, strength: 0.16 },
      grain: 0.12,
    },
  },
  {
    id: 'selenium',
    name: 'Selenium',
    collection: 'darkroom',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      contrast: 0.3,
      lift: -0.04,
      saturation: -1,
      shadowTint: { hue: 282, strength: 0.3 },
      highlightTint: { hue: 214, strength: 0.18 },
      vignette: 0.26,
      grain: 0.1,
    },
  },
  {
    id: 'salt-print',
    name: 'Salt print',
    collection: 'darkroom',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: 0.1,
      contrast: -0.2,
      lift: 0.14,
      saturation: -1,
      shadowTint: { hue: 12, strength: 0.26 },
      highlightTint: { hue: 38, strength: 0.22 },
      vignette: 0.2,
      grain: 0.3,
    },
  },
  {
    id: 'van-dyke',
    name: 'Van Dyke brown',
    collection: 'darkroom',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: -0.1,
      contrast: 0.2,
      lift: 0.08,
      saturation: -1,
      shadowTint: { hue: 8, strength: 0.34 },
      highlightTint: { hue: 32, strength: 0.26 },
      vignette: 0.28,
      grain: 0.2,
    },
  },
  {
    id: 'gum-print',
    name: 'Gum print',
    collection: 'darkroom',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      contrast: -0.14,
      lift: 0.12,
      // Not quite monochrome: a gum print keeps whatever pigment was brushed on,
      // so this one is the exception that leaves some colour in the frame.
      saturation: -0.45,
      shadowTint: { hue: 322, strength: 0.28 },
      highlightTint: { hue: 64, strength: 0.2 },
      vignette: 0.14,
      grain: 0.26,
    },
  },
  {
    id: 'lith-print',
    name: 'Lith print',
    collection: 'darkroom',
    free: false,
    grade: {
      ...NEUTRAL_GRADE,
      exposure: 0.06,
      contrast: 0.4,
      lift: 0.05,
      saturation: -1,
      shadowTint: { hue: 166, strength: 0.24 },
      highlightTint: { hue: 2, strength: 0.28 },
      vignette: 0.3,
      grain: 0.36,
    },
  },
];

export const looksIn = (collection: LookCollectionId): readonly Look[] =>
  LOOKS.filter((entry) => entry.collection === collection);

export const look = (id: string): Look | null => LOOKS.find((entry) => entry.id === id) ?? null;
