import type { BrandIdentityId } from '@chromawave/domain';

/**
 * Runtime brand rasters, generated by `@chromawave/brand-assets` from the same
 * masters as the shipped app icon — so what the user sees in Settings is the icon
 * they get on the home screen, not an approximation of it.
 *
 * Metro resolves the @2x/@3x companions of each file automatically and types a
 * bundled asset as an opaque module id.
 */
export const identityIcons: Record<BrandIdentityId, number> = {
  bandwave: require('../../assets/brand/runtime/bandwave/icon-preview.png'),
  'liquid-lens': require('../../assets/brand/runtime/liquid-lens/icon-preview.png'),
};

/** The mark without a field, for lockups drawn over an existing surface. */
export const identitySymbols: Record<BrandIdentityId, number> = {
  bandwave: require('../../assets/brand/runtime/bandwave/symbol.png'),
  'liquid-lens': require('../../assets/brand/runtime/liquid-lens/symbol.png'),
};

/** iOS superellipse corner ratio, so in-app tiles match the masked home screen icon. */
export const ICON_CORNER_RATIO = 0.2255;
