import { brandGeometry } from '@chromawave/design-tokens';
import { Image } from 'expo-image';
import { StyleSheet, View } from 'react-native';

/**
 * Runtime raster of the mark, generated by `@chromawave/brand-assets` from the
 * same master as the shipped app icon — so the in-app mark and the home screen
 * icon cannot drift apart. Metro resolves the @2x/@3x companions itself.
 */
const markIcon: number = require('../../assets/brand/runtime/icon.png');

export function BrandMark({ size = 42 }: { size?: number }) {
  return (
    <View
      accessibilityLabel="Chroma Wave"
      accessibilityRole="image"
      style={[
        styles.frame,
        { width: size, height: size, borderRadius: size * brandGeometry.cornerRatio },
      ]}
    >
      <Image
        contentFit="cover"
        source={markIcon}
        style={StyleSheet.absoluteFill}
        transition={160}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  frame: {
    overflow: 'hidden',
  },
});
