/**
 * English strings, the source language.
 *
 * BUILD KIT · 08 · LOCALISATION: "Hex values, ΔE numbers, and the wordmark never
 * translate." Those are interpolated at the call site rather than living here, so
 * a translator cannot accidentally localise a hex.
 *
 * Keys are grouped by the flow they belong to, matching the design document's
 * own lettering, so a screen's strings sit together.
 */
export const en = {
  /* ------------------------------------------------------------ A · onboarding */
  'onboarding.welcome.title': 'Colour is a signal.\nStart collecting it.',
  'onboarding.welcome.body':
    'Point at anything. Chroma Wave reads the light and hands you a palette you can actually use.',
  'onboarding.welcome.photoSlot': 'PHOTO · CITY LIGHT',
  'onboarding.how.title': 'Three bands,\nevery time',
  'onboarding.role.dominant': 'Dominant',
  'onboarding.role.dominantBody': 'The colour the scene is actually made of',
  'onboarding.role.support': 'Support',
  'onboarding.role.supportBody': 'What holds it up — surfaces and shadow',
  'onboarding.role.signal': 'Signal',
  'onboarding.role.signalBody': 'The accent that makes people look',
  'onboarding.tune.title': 'Make every band\nyour own',
  'onboarding.tune.body':
    'Tune hue, saturation and light without losing the relationship to the original frame.',
  'onboarding.share.title': 'Keep the photo.\nShare the signal.',
  'onboarding.share.body':
    'Every saved palette stays visual, ready for your library, a set, or a share card.',
  'onboarding.share.previewName': 'Harbour dusk',
  'onboarding.share.previewMeta': '5 COLOURS · READY TO SHARE',
  'onboarding.permission.title': 'We need the camera to read light',
  'onboarding.permission.body':
    'Frames are processed on device and discarded unless you save a capture. Nothing is uploaded by default.',
  'onboarding.permission.reason1': 'On-device colour analysis only',
  'onboarding.permission.reason2': 'No photo library access needed',
  'onboarding.permission.reason3': 'Revoke any time in Settings',
  'onboarding.continue': 'Continue',
  'onboarding.back': 'Back',
  'onboarding.skip': 'Skip intro',
  'onboarding.allowCamera': 'Allow camera',
  'onboarding.importInstead': 'Import a photo instead',
  'onboarding.step': 'Step {current} of {total}',
  'onboarding.saveFailed.title': 'Could not finish setup',
  'onboarding.saveFailed.body': 'Try again. Your choices have not been lost.',

  /* --------------------------------------------------------------- B · capture */
  'capture.close': 'Close capture',
  'capture.liveRead': 'LIVE READ',
  'capture.reading': 'READING',
  'capture.readFailed': 'COULD NOT READ THAT FRAME',
  'capture.import': 'IMPORT',
  'capture.scan': 'SCAN',
  'capture.shutter': 'Capture',
  'capture.shutterHint': 'Extracts a palette from what the camera sees',
  'capture.noDevice': 'NO CAMERA ON THIS DEVICE',
  'capture.cameraNeeded': 'CAMERA ACCESS NEEDED',
  'capture.flash': 'FLASH',
  'capture.flash.off': 'OFF',
  'capture.flash.on': 'ON',
  'capture.flash.auto': 'AUTO',
  'capture.autoWb': 'AUTO WB',
  'capture.mode.live': 'LIVE',
  'capture.mode.photo': 'PHOTO',
  'capture.mode.scan': 'SCAN',
  'capture.permission.allowBody': 'Allow camera access to start reading colour.',
  'capture.permission.deniedBody':
    'Camera access is off. Turn it on in Settings, or import a photo instead.',
  'capture.notNow': 'Not now',

  'result.capture': 'CAPTURE',
  'result.close': 'CLOSE',
  'result.retake': 'RETAKE',
  'result.confidence': 'CONF {percent}%',
  'result.read': 'READ {stability}',
  'result.tune': 'Tune',
  'result.save': 'Save palette',
  'result.copy': 'COPY',
  'result.copyLabel': 'Copy {hex}',
  'result.copyHint': 'Copies {hex}',
  'result.none.title': 'No capture',
  'result.none.body': 'That capture has already been saved or discarded.',
  'result.none.action': 'Back to library',

  'tune.title': 'Tune bands',
  'tune.cancel': 'Cancel',
  'tune.apply': 'Apply',
  'tune.before': 'BEFORE',
  'tune.after': 'AFTER',
  'tune.hue': 'HUE',
  'tune.saturation': 'SATURATION',
  'tune.luminance': 'LUMINANCE',
  'tune.preset.neutralise': 'NEUTRALISE',
  'tune.preset.warm': 'WARM +5',
  'tune.preset.cinema': 'CINEMA',
  'tune.preset.reset': 'RESET',
  'tune.contrast.title': 'Contrast check',
  'tune.contrast.pass': 'PASS',
  'tune.contrast.fail': 'FAIL',

  'palette.back': 'BACK',
  'palette.more': 'More actions',
  'palette.addTag': 'TAG',
  'palette.addTag.confirm': 'Add tag',
  'palette.addTag.placeholder': 'One word, lower case',
  'palette.rename.placeholder': 'Palette name',
  'palette.menu.rename': 'Rename',
  'palette.menu.pin': 'Pin to top',
  'palette.menu.unpin': 'Remove pin',
  'palette.menu.duplicate': 'Duplicate',
  'palette.menu.delete': 'Delete palette',
  'palette.copyName': '{name} copy',
  'palette.delete.title': 'Delete this palette?',
  'palette.delete.body': '“{name}” will be removed from your library. This cannot be undone.',
  'palette.delete.confirm': 'Delete',
  'palette.writeFailed': 'Could not save the change',
  'palette.writeFailedDetail': 'The palette is unchanged',
  'palette.share': 'Share palette',
  'palette.saved': 'saved {age} ago',
  'palette.colourCount': '{count} colours',
  'palette.loading': 'Loading',
  'palette.tools': 'TOOLS',
  'palette.widgets': 'Widgets',

  /* ------------------------------------------------------- C · library, explore */
  'library.title': 'Library',
  'library.meta': '{palettes} palettes · {collections} collections',
  'library.search': 'Search the library',
  'library.filter.all': 'ALL',
  'library.filter.recent': 'RECENT',
  'library.filter.pinned': 'PINNED',
  'library.resultCount': '{count} of {total}',
  'library.empty.title': 'Nothing captured yet',
  'library.empty.body': 'Point at something with colour in it. It takes about two seconds.',
  'library.empty.action': 'Open camera',
  'library.noResults.title': 'No matches',
  'library.noResults.body': 'Nothing in this filter yet. Try another, or capture something new.',
  'library.card.meta': '{count} colours · {age}',
  'library.card.hint': 'Opens the palette',

  'explore.title': 'Explore',
  'explore.searchPlaceholder': 'Search colour, tag or hex',
  'explore.editorial': 'EDITORIAL · WEEKLY',
  'explore.inYourLibrary': 'In your library',
  'explore.resultCount': '{count} found',
  'explore.noResults': 'Nothing matches “{query}”.',

  /* ---------------------------------------- C1 · the landing carousel */
  'hero.label': 'Featured',
  'hero.capture.eyebrow': 'START HERE',
  'hero.capture.title': 'Read the light in front of you',
  'hero.capture.body': 'Point at anything with colour in it. A palette comes back in two seconds.',
  'hero.capture.cta': 'Open camera',
  'hero.trending.eyebrow': 'RISING THIS WEEK',
  'hero.trending.cta': 'See trending',
  'hero.studio.eyebrow': 'GRADIENT STUDIO',
  'hero.studio.title': 'Turn a palette into a surface',
  'hero.studio.body': 'Take {name} into the studio and export it as a wallpaper.',
  'hero.studio.cta': 'Open studio',
  'hero.pro.eyebrow': 'CHROMA WAVE PRO',
  'hero.pro.title': 'Unlock the complete wave',
  'hero.pro.body': 'Merged sets, watermark-free cards, and ASE, JSON and P3 export.',
  'hero.pro.cta': 'See Pro',

  /* ---------------------------------- discovery filters · library + trending */
  'filter.toggle': 'FILTERS',
  'filter.active': '{count} ON',
  'filter.reset': 'RESET',
  'filter.expand': 'Show colour and style filters',
  'filter.collapse': 'Hide colour and style filters',
  'filter.group.mood': 'COLOUR MOOD',
  'filter.group.style': 'STYLE',
  'filter.group.category': 'WHERE FROM',
  'filter.group.sort': 'ORDER',
  'library.mood.warm': 'WARM',
  'library.mood.cool': 'COOL',
  'library.mood.pastel': 'PASTEL',
  'library.mood.monochrome': 'MONOCHROME',
  'library.mood.vibrant': 'VIBRANT',
  'library.style.minimal': 'MINIMAL',
  'library.style.editorial': 'EDITORIAL',
  'library.style.retro': 'RETRO',
  'library.style.futuristic': 'FUTURISTIC',
  'library.style.organic': 'ORGANIC',

  /* ------------------------------------------------------------ C4 · trending */
  'trending.title': 'Trending',
  'trending.meta': '{count}K SAVES · @{author}',
  'trending.saves': '{count}K SAVES',
  'trending.homeMeta': 'What the app is saving this week',
  'trending.screenMeta': '{count} palettes · refreshed daily',
  'trending.search': 'Search trending palettes',
  'trending.seeAll': 'SEE ALL',
  'trending.back': 'LIBRARY',
  'trending.save': 'SAVE',
  'trending.saved': 'SAVED',
  'trending.resultCount': '{count} found',
  'trending.category.all': 'ALL',
  'trending.category.editorial': 'EDITORIAL',
  'trending.category.urban': 'URBAN',
  'trending.category.nature': 'NATURE',
  'trending.category.interior': 'INTERIOR',
  'trending.category.archive': 'ARCHIVE',
  'trending.sort.popular': 'POPULAR',
  'trending.sort.new': 'NEWEST',
  'trending.loading': 'Loading trending palettes',
  'trending.loadMore': 'Load more',
  'trending.empty.title': 'Nothing trending here',
  'trending.empty.body':
    'No palette matches this combination yet. Loosen one filter, or reset them all.',
  'trending.error.title': 'Could not load trending',
  'trending.error.body': 'The feed did not come back. Nothing in your library was touched.',
  'trending.retry': 'Try again',
  'trending.saveFailed': 'Could not save',
  'trending.saveFailedDetail': 'Try again in a moment',

  'sets.title': 'Sets',
  'sets.meta': '{count} collections',
  'sets.empty.title': 'No sets yet',
  'sets.empty.body':
    'Group palettes into a set to compare them side by side and export them together.',
  'sets.empty.action': 'Open library',
  'sets.create': 'New set',
  'sets.createFailed': 'Could not create the set',
  'sets.createFailedDetail': 'Nothing was saved',
  'sets.new.title': 'New set',
  'sets.new.nameLabel': 'Set name',
  'sets.new.namePlaceholder': 'Name this set',
  'sets.new.saving': 'Saving…',
  'sets.new.seeded': 'Starts with {count} pinned palettes',
  'sets.new.seededEmpty': 'Starts empty',
  'sets.new.startsWith': 'STARTS WITH',
  'sets.new.hint': 'Nothing is pinned, so this set starts empty. Add palettes from your library.',
  'collection.back': 'LIBRARY',
  'collection.edit': 'EDIT',
  'collection.meta.shared': '{count} palettes · shared with {people} people',
  'collection.meta.private': '{count} palettes · private',
  'collection.exportSet': 'EXPORT SET',
  'collection.invite': 'INVITE',
  'collection.rename': 'RENAME',
  'collection.renamePlaceholder': 'Set name',
  'collection.deleteSet': 'DELETE SET',
  'collection.delete.title': 'Delete this set?',
  'collection.delete.body': '“{name}” will be removed. The palettes in it are kept.',
  'collection.removePalette': 'Remove {name} from this set',
  'collection.inviteCopied': 'Link copied. It opens this set on a device that already has it.',
  'collection.addedByYou': 'added by you',
  'collection.system': 'THE SYSTEM',
  'collection.system.meta': 'Merged from {count} palettes',
  'collection.system.empty': 'Add palettes and this set builds one system from all of them.',
  'collection.pairings': 'PAIRINGS',
  'collection.pairingSample': 'Aa',
  'collection.pairingRatio': '{ratio}:1',
  'collection.pairingLabel': '{hex} on {background}, ratio {ratio} to 1',
  'collection.gap.missing-signal': 'Nothing here is saturated enough to carry an accent.',
  'collection.gap.narrow-lightness': 'Everything sits at one level, so nothing carries contrast.',
  'collection.gap.no-safe-pairing': 'No two colours here can hold text on one another.',
  'collection.gap.action': 'Capture one',
  'collection.gap.none': 'This set works as a system.',
  'collection.members': 'IN THIS SET',
  'sets.openGaps': '{count} open',
  'sets.complete': 'Complete',

  'share.title': 'Share “{name}”',
  'share.format.1x1': '1:1 POST',
  'share.format.4x5': '4:5 FEED',
  'share.format.9x16': '9:16 STORY',
  'share.includePhoto': 'Include photo',
  'share.showHex': 'Show hex values',
  'share.removeWatermark': 'Remove watermark',
  'share.saveImage': 'Save image',
  'share.share': 'Share…',

  /* ------------------------------------------------------------ D · pro, account */
  'paywall.close': 'Close',
  'paywall.title': 'Unlock the\ncomplete wave',
  'paywall.body':
    'Third band, unlimited captures, and export in the formats your tools actually read.',
  'paywall.benefit1': 'Unlimited palettes & collections',
  'paywall.benefit2': 'Merge sets, ASE / JSON / P3 export',
  'paywall.benefit3': 'Watermark-free share cards',
  'paywall.monthly': 'MONTHLY',
  'paywall.yearly': 'YEARLY',
  'paywall.perMonth': 'PER MONTH',
  'paywall.perMonthEquivalent': '{price} / MONTH',
  'paywall.save': 'SAVE 40%',
  'paywall.cta': 'Start 7 days free',
  'paywall.restore': 'RESTORE',
  'paywall.restoreNone': 'No previous purchase found on this Apple ID.',
  'paywall.terms': 'TERMS',
  'paywall.privacy': 'PRIVACY',
  'paywall.smallPrintYearly':
    'Then {price}/year. Cancel any time in the App Store; your saved palettes stay yours either way.',
  'paywall.smallPrintMonthly':
    'Then {price}/month. Cancel any time in the App Store; your saved palettes stay yours either way.',

  'you.title': 'You',
  'you.meta': 'Local library · this device',
  'you.signature.eyebrow': 'YOUR COLOUR SIGNATURE',
  'you.signature.body': 'Built from every capture you have kept.',
  'you.signature.empty': 'Capture something and this builds itself.',
  'you.signature.label': 'Your colour signature',
  'you.stat.palettes': 'PALETTES',
  'you.stat.pinned': 'PINNED',
  'you.stat.colours': 'COLOURS',
  'you.stat.collections': 'SETS',
  'you.stat.thisMonth': 'THIS MONTH',
  'you.stat.hint': 'Opens the library',
  'you.taste.title': 'What you keep',
  'you.taste.meta': 'Read from your own captures, not from a survey',
  'you.taste.empty': 'Two or three captures and this fills in.',
  'you.taste.count': '{count} palettes',
  'you.taste.hint': 'Filters the library by this',
  'you.collections.title': 'Collections',
  'you.collections.empty': 'Group palettes into a set to compare and export them together.',
  'you.collections.count': '{count} palettes',
  'you.recent.title': 'Recently captured',
  'you.recent.empty': 'Your captures will land here.',
  'you.controls.title': 'Controls',
  'you.controls.meta': 'Capture, colour and this device',
  'you.more.title': 'More',
  'you.seeAll': 'SEE ALL',
  'you.newSet': 'New set',
  'you.colourSpace': 'Colour space',
  'you.defaultExport': 'Default export',
  'you.haptics': 'Haptics on capture',
  'you.sound': 'Sound effects',
  'you.backdrop': 'Animated backdrop',
  'you.reminder': 'Daily reminder',
  'you.language': 'Language',
  'you.languageSwitch': 'Switch between English and Vietnamese',
  'you.open': 'OPEN',
  'you.unread': '{count} NEW',
  'you.version': 'V{version} · PRIVACY · SUPPORT',

  /* --------------------------------------------------------------- G · deeper */
  'scan.exit': 'EXIT SCAN',
  'scan.pinned': '{count} PINNED',
  'scan.pinnedWhileWalking': 'PINNED WHILE YOU WALK',
  'scan.now': 'NOW {hex}',
  'scan.build': 'Build palette from {count} pins',
  'scan.pinLabel': 'Pin a colour',
  'scan.pinHint': 'Pins the colour under the reticle',
  'scan.removePin': 'Remove {hex}',
  'scan.liveScene': 'LIVE SCENE',

  'import.title': 'Pick points',
  'import.cancel': 'Cancel',
  'import.extract': 'Extract',
  'import.photo': 'IMPORTED PHOTO',
  'import.decoding': 'DECODING',
  'import.reading': 'READING THE WHOLE PHOTO',
  'import.autoRead': '{count} COLOURS FOUND · TAP TO REFINE',
  'import.failed': 'COULD NOT READ THIS PHOTO',
  'import.points': 'PINCH TO ZOOM · {count}/{max} POINTS',
  'import.radius': 'SAMPLE RADIUS',
  'import.radiusValue': '{px} PX · AVERAGED',
  'import.mode.manual': 'MANUAL',
  'import.mode.auto': 'AUTO',
  'import.mode.edges': 'EDGES',
  'import.choosePhoto': 'CHOOSE PHOTO',
  'import.changePhoto': 'CHANGE PHOTO',
  'import.removePoint': 'Remove {hex}',
  'import.hint': 'Tap the photo to add at least two sample points. Tap a point to remove it.',
  'import.tapLabel': 'Photo, tap to sample',
  'import.tapHint': 'Adds a sample point',

  'compare.title': 'Compare',
  'compare.meta': '2 palettes · ΔE matrix',
  'compare.matrixLabel': 'PERCEPTUAL DISTANCE ΔE00',
  'compare.closest': 'Closest pair',
  'compare.swap': 'SWAP',
  'compare.temperature': 'Temperature',
  'compare.tempCool': 'cool 4200K',
  'compare.tempWarm': 'warm 2700K',
  'compare.addThird': 'Add third',
  'compare.choose': 'Compare against',
  'compare.swapSides': 'Swap A and B',
  'compare.mergedName': '{first} × {second}',
  'compare.merge': 'Merge into set',
  'compare.needTwo': 'Compare needs two saved palettes.',
  'compare.cellLabel': '{from} to {to}, delta E {value}',

  'contrast.title': 'Contrast check',
  'contrast.meta': '{name} · WCAG 2.2',
  'contrast.largeSample': 'Large text sample',
  'contrast.largeBody': 'Body copy at 14px on the dominant band.',
  'contrast.signalOnInk': 'Signal on ink',
  'contrast.signalBody': 'Body copy at 14px on surface ink.',
  'contrast.onDominant': 'ON DOMINANT',
  'contrast.onSurface': 'ON SURFACE',
  'contrast.onPaper': 'ON PAPER',
  'contrast.suggestedFix': 'SUGGESTED FIX',
  'contrast.applyFix': 'Apply this fix',
  'contrast.fixNote': 'Luminance {delta}, hue held',
  'contrast.simulationNote':
    '{name} simulation is a preview only — verdicts above use true luminance',

  'gradient.title': 'Gradient studio',
  'gradient.close': 'Close',
  'gradient.save': 'Save',
  'gradient.angle': 'ANGLE',
  'gradient.interpolation': 'INTERPOLATION',
  'gradient.grain': 'Add film grain',
  'gradient.wallpaper': 'WALLPAPER',
  'gradient.exportFailed': 'Could not export',
  'gradient.exportFailedDetail': 'The gradient could not be rendered to a file',

  'theme.title': 'See it applied',
  'theme.meta': '{name} as UI',
  'theme.dashboard': 'Dashboard',
  'theme.uptime': 'UPTIME',
  'theme.sessions': 'SESSIONS',
  'theme.alerts': 'ALERTS',
  'theme.primaryAction': 'Primary action',
  'theme.webHeadline': 'Colour that carries',
  'theme.posterTitle': 'FIELD\nNOTES',
  'theme.posterMeta': 'EXHIBITION · NO. 04',
  'theme.slideEyebrow': 'QUARTERLY REVIEW',
  'theme.slideTitle': 'What the light told us',
  'theme.roleMapping': 'ROLE MAPPING · AUTO',
  'theme.export': 'Export theme',
  'theme.unreadable': 'ON-SURFACE FAILS AA AGAINST SURFACE — TUNE BEFORE EXPORT',

  'export.title': 'Export',
  'export.close': 'Close',
  'export.copy': 'Copy',
  'export.includeTints': 'Include tints & shades',
  'export.p3': 'Display P3 fallbacks',
  'export.semanticNames': 'Semantic role names',
  'export.sendTo': 'SEND TO',
  'export.figma': 'Figma library',
  'export.gist': 'GitHub gist',
  'export.copyToClipboard': 'Copy to clipboard',
  'export.openFailed': 'Could not open the destination',
  'export.openFailedDetail': 'The code is on your clipboard',

  'widgets.close': 'DONE',

  'activity.title': 'Activity',
  'activity.markRead': 'MARK ALL READ',
  'activity.allRead': 'ALL READ',
  'activity.captured': 'CAPTURED {age} AGO',
  'activity.none.title': 'No shared activity',
  'activity.none.body':
    'Sharing sets and following creators need an account. Your own captures are all here in the recap below.',
  'activity.thisMonth': 'THIS MONTH',
  'activity.recap': 'Your colour year',
  'activity.recapEmpty': 'Nothing captured yet this month.',
  'activity.recapSummary':
    'You captured {count} palettes. {leader} is winning — {runnerUp} is closing.',
  'activity.recapSummaryOne': 'You captured 1 palette.',
  'activity.barLabel': '{label}, {count} palettes',

  /* ---------------------------------------------------------------- E · states */
  'state.loading': 'Loading',
  'state.offline.title': 'You’re offline',
  'state.offline.body':
    'Capture still works — extraction runs on device. Sync resumes automatically.',
  'state.nothing.title': 'Nothing here',
  'state.nothing.body': 'That screen has moved or never existed.',
  'state.nothing.action': 'Back to library',
  'state.tool.title': 'Nothing to work on',
  'state.tool.body': 'Capture a palette first, then open this from its detail screen.',
  'state.tool.action': 'Open library',
  'toast.saved': 'Palette saved',
  'toast.undo': 'UNDO',

  /* ------------------------------------------------------------------- shared */
  'common.pro': 'PRO',
  'common.cancel': 'Cancel',
  'common.save': 'Save',
  'common.done': 'DONE',
  'common.working': 'WORKING',
  'common.selected': 'Selected',
  'common.css': 'CSS',
  'common.svg': 'SVG',
  'common.ase': 'ASE',
  'common.json': 'JSON',
  'common.proJson': 'PRO · JSON',
  'common.stability.stable': 'stable',
  'common.stability.drifting': 'drifting',
  'common.stability.unstable': 'unstable',
} as const;

export type MessageKey = keyof typeof en;
