import type { MessageKey } from './en';

/**
 * Vietnamese.
 *
 * BUILD KIT · 08: "Vietnamese runs ~25% longer — every button and chip must
 * survive a 30% string expansion without truncating." Where a control is tight,
 * the Vietnamese is deliberately the shorter of two valid phrasings rather than
 * the literal translation; `localization.test.ts` enforces the budgets.
 *
 * Hex values, ΔE numbers and the wordmark are never translated — they arrive as
 * interpolated parameters, so no key here contains one.
 */
export const vi: Record<MessageKey, string> = {
  /* ------------------------------------------------------------ A · onboarding */
  'onboarding.welcome.title': 'Màu là một tín hiệu.\nBắt đầu thu thập.',
  'onboarding.welcome.body':
    'Hướng vào bất cứ thứ gì. CHROMAWAVE đọc ánh sáng và trả về bảng màu bạn dùng được ngay.',
  'onboarding.welcome.photoSlot': 'ẢNH · ÁNH ĐÈN PHỐ',
  'onboarding.how.title': 'Ba dải màu,\nmọi lần chụp',
  'onboarding.role.dominant': 'Chủ đạo',
  'onboarding.role.dominantBody': 'Màu mà khung cảnh thực sự được tạo nên từ đó',
  'onboarding.role.support': 'Nền đỡ',
  'onboarding.role.supportBody': 'Thứ giữ nó lại — bề mặt và bóng tối',
  'onboarding.role.signal': 'Tín hiệu',
  'onboarding.role.signalBody': 'Điểm nhấn khiến người ta phải nhìn',
  'onboarding.permission.title': 'Cần camera để đọc ánh sáng',
  'onboarding.permission.body':
    'Khung hình được xử lý trên máy và bị loại bỏ trừ khi bạn lưu. Không có gì được tải lên theo mặc định.',
  'onboarding.permission.reason1': 'Chỉ phân tích màu trên máy',
  'onboarding.permission.reason2': 'Không cần quyền vào thư viện ảnh',
  'onboarding.permission.reason3': 'Thu hồi bất cứ lúc nào trong Cài đặt',
  'onboarding.continue': 'Tiếp tục',
  'onboarding.skip': 'Bỏ qua',
  'onboarding.allowCamera': 'Cho phép camera',
  'onboarding.importInstead': 'Chọn ảnh có sẵn',
  'onboarding.step': 'Bước {current} / {total}',

  /* --------------------------------------------------------------- B · capture */
  'capture.close': 'Đóng',
  'capture.liveRead': 'ĐANG ĐỌC',
  'capture.reading': 'ĐANG ĐỌC',
  'capture.import': 'CHỌN ẢNH',
  'capture.scan': 'QUÉT',
  'capture.shutter': 'Chụp',
  'capture.shutterHint': 'Trích bảng màu từ những gì camera thấy',
  'capture.noDevice': 'MÁY NÀY KHÔNG CÓ CAMERA',
  'capture.cameraNeeded': 'CẦN QUYỀN CAMERA',
  'capture.flash': 'ĐÈN',
  'capture.ratio': '4:5',
  'capture.autoWb': 'WB TỰ ĐỘNG',
  'capture.mode.live': 'TRỰC TIẾP',
  'capture.mode.photo': 'ẢNH',
  'capture.mode.scan': 'QUÉT',
  'capture.permission.allowBody': 'Cho phép camera để bắt đầu đọc màu.',
  'capture.permission.deniedBody':
    'Camera đang tắt. Bật lại trong Cài đặt, hoặc chọn một ảnh có sẵn.',
  'capture.notNow': 'Để sau',

  'result.capture': 'ẢNH CHỤP',
  'result.close': '✕ ĐÓNG',
  'result.retake': 'CHỤP LẠI',
  'result.confidence': 'TIN CẬY {percent}%',
  'result.read': 'ĐỘ ĐỌC {stability}',
  'result.tune': 'Tinh chỉnh',
  'result.save': 'Lưu bảng màu',
  'result.copy': 'CHÉP',
  'result.copyLabel': 'Chép {hex}',
  'result.copyHint': 'Chép {hex} vào clipboard',
  'result.none.title': 'Không có ảnh chụp',
  'result.none.body': 'Ảnh chụp đó đã được lưu hoặc đã bị bỏ.',
  'result.none.action': 'Về thư viện',

  'tune.title': 'Tinh chỉnh dải',
  'tune.cancel': 'Huỷ',
  'tune.apply': 'Áp dụng',
  'tune.before': 'TRƯỚC',
  'tune.after': 'SAU',
  'tune.hue': 'TÔNG',
  'tune.saturation': 'ĐỘ BÃO HOÀ',
  'tune.luminance': 'ĐỘ SÁNG',
  'tune.preset.neutralise': 'TRUNG TÍNH',
  'tune.preset.warm': 'ẤM +5',
  'tune.preset.cinema': 'ĐIỆN ẢNH',
  'tune.preset.reset': 'ĐẶT LẠI',
  'tune.contrast.title': 'Kiểm tra tương phản',
  'tune.contrast.pass': 'ĐẠT',
  'tune.contrast.fail': 'KHÔNG ĐẠT',

  'palette.back': '‹ QUAY LẠI',
  'palette.more': 'Thêm tuỳ chọn',
  'palette.addTag': '+ THẺ',
  'palette.share': 'Chia sẻ bảng màu',
  'palette.saved': 'lưu {age} trước',
  'palette.colourCount': '{count} màu',
  'palette.loading': 'Đang tải',

  /* ------------------------------------------------------- C · library, explore */
  'library.title': 'Thư viện',
  'library.meta': '{palettes} bảng màu · {collections} bộ',
  'library.search': 'Tìm trong thư viện',
  'library.filter.all': 'TẤT CẢ',
  'library.filter.recent': 'GẦN ĐÂY',
  'library.filter.pinned': 'ĐÃ GHIM',
  'library.filter.warm': 'MÀU ẤM',
  'library.empty.title': 'Chưa chụp gì cả',
  'library.empty.body': 'Hướng vào thứ gì có màu. Chỉ mất khoảng hai giây.',
  'library.empty.action': 'Mở camera',
  'library.noResults.title': 'Không có kết quả',
  'library.noResults.body': 'Bộ lọc này chưa có gì. Thử bộ lọc khác, hoặc chụp mới.',
  'library.card.meta': '{count} màu · {age}',
  'library.card.hint': 'Mở bảng màu',

  'explore.title': 'Khám phá',
  'explore.searchPlaceholder': 'Tìm màu, thẻ hoặc mã hex',
  'explore.editorial': 'CHUYÊN ĐỀ · HÀNG TUẦN',
  'explore.featured': 'Ánh sáng công nghiệp Bắc Âu',
  'explore.trending': 'Thịnh hành',
  'explore.seeAll': 'XEM HẾT',
  'explore.save': 'LƯU',
  'explore.saves': '{count}K LƯU · @{author}',

  'sets.title': 'Bộ màu',
  'sets.meta': '{count} bộ',
  'sets.empty.title': 'Chưa có bộ nào',
  'sets.empty.body': 'Nhóm các bảng màu thành một bộ để so sánh cạnh nhau và xuất cùng lúc.',
  'sets.empty.action': 'Mở thư viện',
  'collection.back': '‹ THƯ VIỆN',
  'collection.edit': 'SỬA',
  'collection.meta.shared': '{count} bảng màu · chia sẻ với {people} người',
  'collection.meta.private': '{count} bảng màu · riêng tư',
  'collection.mergeAll': 'GỘP HẾT',
  'collection.exportSet': 'XUẤT BỘ',
  'collection.invite': 'MỜI',
  'collection.addedByYou': 'bạn đã thêm',
  'collection.merged': 'BỘ ĐÃ GỘP · PRO',
  'collection.mergedLocked': 'BỘ ĐÃ GỘP · CẦN PRO',
  'collection.mergedBody': 'Gộp bộ này để tạo một bảng màu từ tất cả.',
  'collection.mergedLockedBody': 'Pro gộp cả một bộ thành một bảng màu.',

  'share.title': 'Chia sẻ “{name}”',
  'share.format.1x1': '1:1 BÀI ĐĂNG',
  'share.format.4x5': '4:5 DÒNG TIN',
  'share.format.9x16': '9:16 STORY',
  'share.includePhoto': 'Kèm ảnh',
  'share.showHex': 'Hiện mã hex',
  'share.removeWatermark': 'Bỏ watermark',
  'share.saveImage': 'Lưu ảnh',
  'share.share': 'Chia sẻ…',

  /* ------------------------------------------------------------ D · pro, account */
  'paywall.close': 'Đóng',
  'paywall.title': 'Mở trọn\nbộ ba dải',
  'paywall.body': 'Dải thứ ba, chụp không giới hạn, và xuất ra đúng định dạng công cụ bạn dùng.',
  'paywall.benefit1': 'Bảng màu & bộ màu không giới hạn',
  'paywall.benefit2': 'Gộp bộ, xuất ASE / JSON / P3',
  'paywall.benefit3': 'Thẻ chia sẻ không watermark',
  'paywall.monthly': 'HÀNG THÁNG',
  'paywall.yearly': 'HÀNG NĂM',
  'paywall.perMonth': 'MỖI THÁNG',
  'paywall.perMonthEquivalent': '{price} / THÁNG',
  'paywall.save': 'TIẾT KIỆM 40%',
  'paywall.cta': 'Dùng thử 7 ngày',
  'paywall.restore': 'PHỤC HỒI',
  'paywall.terms': 'ĐIỀU KHOẢN',
  'paywall.privacy': 'BẢO MẬT',
  'paywall.smallPrintYearly':
    'Sau đó {price}/năm. Huỷ bất cứ lúc nào trên App Store; bảng màu đã lưu vẫn là của bạn.',
  'paywall.smallPrintMonthly':
    'Sau đó {price}/tháng. Huỷ bất cứ lúc nào trên App Store; bảng màu đã lưu vẫn là của bạn.',

  'you.title': 'Bạn',
  'you.meta': 'Thư viện cục bộ · máy này',
  'you.stat.palettes': 'BẢNG MÀU',
  'you.stat.pinned': 'ĐÃ GHIM',
  'you.stat.colours': 'MÀU',
  'you.colourSpace': 'Không gian màu',
  'you.defaultExport': 'Xuất mặc định',
  'you.haptics': 'Rung khi chụp',
  'you.sound': 'Âm thanh',
  'you.reminder': 'Nhắc hằng ngày',
  'you.language': 'Ngôn ngữ',
  'you.version': 'V{version} · BẢO MẬT · HỖ TRỢ',

  /* --------------------------------------------------------------- G · deeper */
  'scan.exit': '✕ THOÁT',
  'scan.pinned': 'ĐÃ GHIM {count}',
  'scan.pinnedWhileWalking': 'GHIM TRONG KHI DI CHUYỂN',
  'scan.now': 'HIỆN TẠI {hex}',
  'scan.build': 'Tạo bảng màu từ {count} ghim',
  'scan.pinLabel': 'Ghim một màu',
  'scan.pinHint': 'Ghim màu ở giữa khung ngắm',
  'scan.removePin': 'Bỏ {hex}',
  'scan.liveScene': 'KHUNG CẢNH TRỰC TIẾP',

  'import.title': 'Chọn điểm',
  'import.cancel': 'Huỷ',
  'import.extract': 'Trích',
  'import.photo': 'ẢNH ĐÃ CHỌN',
  'import.decoding': 'ĐANG GIẢI MÃ',
  'import.failed': 'KHÔNG ĐỌC ĐƯỢC ẢNH NÀY',
  'import.points': 'CHỤM ĐỂ ZOOM · {count}/{max} ĐIỂM',
  'import.radius': 'BÁN KÍNH LẤY MẪU',
  'import.radiusValue': '{px} PX · TRUNG BÌNH',
  'import.mode.manual': 'THỦ CÔNG',
  'import.mode.auto': 'TỰ ĐỘNG 5',
  'import.mode.edges': 'BIÊN',
  'import.hint': 'Chạm vào ảnh để thêm ít nhất hai điểm lấy mẫu.',
  'import.tapLabel': 'Ảnh, chạm để lấy mẫu',
  'import.tapHint': 'Thêm một điểm lấy mẫu',

  'compare.title': 'So sánh',
  'compare.meta': '2 bảng màu · ma trận ΔE',
  'compare.matrixLabel': 'KHOẢNG CÁCH THỊ GIÁC ΔE00',
  'compare.closest': 'Cặp gần nhất',
  'compare.swap': 'ĐỔI →',
  'compare.temperature': 'Nhiệt màu',
  'compare.tempCool': 'lạnh 4200K',
  'compare.tempWarm': 'ấm 2700K',
  'compare.addThird': 'Thêm thứ ba',
  'compare.merge': 'Gộp thành bộ',
  'compare.needTwo': 'So sánh cần hai bảng màu đã lưu.',
  'compare.cellLabel': '{from} tới {to}, delta E {value}',

  'contrast.title': 'Kiểm tra tương phản',
  'contrast.meta': '{name} · WCAG 2.2',
  'contrast.largeSample': 'Mẫu chữ lớn',
  'contrast.largeBody': 'Chữ nội dung 14px trên dải chủ đạo.',
  'contrast.signalOnInk': 'Tín hiệu trên nền mực',
  'contrast.signalBody': 'Chữ nội dung 14px trên nền mực.',
  'contrast.onDominant': 'TRÊN CHỦ ĐẠO',
  'contrast.onSurface': 'TRÊN NỀN',
  'contrast.onPaper': 'TRÊN GIẤY',
  'contrast.suggestedFix': 'ĐỀ XUẤT SỬA',
  'contrast.fixNote': 'Độ sáng {delta}, giữ tông',
  'contrast.simulationNote': 'Mô phỏng {name} chỉ để xem trước — kết luận ở trên dùng độ sáng thật',

  'gradient.title': 'Xưởng gradient',
  'gradient.close': 'Đóng',
  'gradient.save': 'Lưu',
  'gradient.angle': 'GÓC',
  'gradient.interpolation': 'NỘI SUY',
  'gradient.grain': 'Thêm hạt phim',
  'gradient.wallpaper': 'HÌNH NỀN',

  'theme.title': 'Xem khi áp dụng',
  'theme.meta': '{name} → xem trước UI',
  'theme.dashboard': 'Bảng điều khiển',
  'theme.uptime': 'HOẠT ĐỘNG',
  'theme.sessions': 'PHIÊN',
  'theme.alerts': 'CẢNH BÁO',
  'theme.primaryAction': 'Hành động chính',
  'theme.roleMapping': 'GÁN VAI TRÒ · TỰ ĐỘNG',
  'theme.export': 'Xuất giao diện',
  'theme.unreadable': 'CHỮ TRÊN NỀN KHÔNG ĐẠT AA — TINH CHỈNH TRƯỚC KHI XUẤT',

  'export.title': 'Xuất',
  'export.close': 'Đóng',
  'export.copy': 'Chép',
  'export.includeTints': 'Kèm màu nhạt & đậm',
  'export.p3': 'Dự phòng Display P3',
  'export.semanticNames': 'Tên vai trò ngữ nghĩa',
  'export.sendTo': 'GỬI TỚI',
  'export.figma': 'Thư viện Figma',
  'export.gist': 'GitHub gist',
  'export.copyToClipboard': 'Chép vào clipboard',

  'activity.title': 'Hoạt động',
  'activity.markRead': 'ĐÁNH DẤU ĐÃ ĐỌC',
  'activity.none.title': 'Chưa có hoạt động chung',
  'activity.none.body':
    'Chia sẻ bộ màu và theo dõi người khác cần có tài khoản. Ảnh chụp của bạn đều ở phần tổng kết dưới đây.',
  'activity.thisMonth': 'THÁNG NÀY',
  'activity.recap': 'Năm màu sắc của bạn',
  'activity.recapEmpty': 'Tháng này chưa chụp gì.',
  'activity.recapSummary': 'Bạn đã chụp {count} bảng màu. {leader} đang dẫn — {runnerUp} đang bám.',
  'activity.recapSummaryOne': 'Bạn đã chụp 1 bảng màu.',
  'activity.barLabel': '{label}, {count} bảng màu',

  /* ---------------------------------------------------------------- E · states */
  'state.loading': 'Đang tải',
  'state.offline.title': 'Bạn đang offline',
  'state.offline.body': 'Vẫn chụp được — việc trích màu chạy trên máy. Đồng bộ sẽ tự tiếp tục.',
  'state.nothing.title': 'Không có gì ở đây',
  'state.nothing.body': 'Màn hình đó đã chuyển đi hoặc chưa từng tồn tại.',
  'state.nothing.action': 'Về thư viện',
  'state.tool.title': 'Chưa có gì để làm',
  'state.tool.body': 'Hãy chụp một bảng màu trước, rồi mở mục này từ trang chi tiết.',
  'state.tool.action': 'Mở thư viện',
  'toast.saved': 'Đã lưu bảng màu',
  'toast.undo': 'HOÀN TÁC',

  /* ------------------------------------------------------------------- shared */
  'common.pro': 'PRO',
  'common.selected': 'Đã chọn',
  'common.css': 'CSS',
  'common.svg': 'SVG',
  'common.ase': 'ASE',
  'common.json': 'JSON',
  'common.proJson': 'PRO · JSON',
  'common.stability.stable': 'ổn định',
  'common.stability.drifting': 'đang lệch',
  'common.stability.unstable': 'không ổn',
};
