import type { MessageKey } from './en';

/**
 * Vietnamese.
 *
 * BUILD KIT · 08: "Vietnamese runs ~25% longer — every button and chip must
 * survive a 30% string expansion without truncating." Where a control is tight,
 * the Vietnamese is deliberately the shorter of two valid phrasings rather than
 * the literal translation; `localization.test.ts` enforces the budgets.
 *
 * Hex values, ΔE numbers and the wordmark are never translated — they arrive as
 * interpolated parameters, so no key here contains one.
 */
export const vi: Record<MessageKey, string> = {
  /* ------------------------------------------------------------ A · onboarding */
  'onboarding.welcome.title': 'Màu là một tín hiệu.\nBắt đầu thu thập.',
  'onboarding.welcome.body':
    'Hướng vào bất cứ thứ gì. Chroma Wave đọc ánh sáng và trả về bảng màu bạn dùng được ngay.',
  'onboarding.welcome.photoSlot': 'ẢNH · ÁNH ĐÈN PHỐ',
  'onboarding.how.title': 'Ba dải màu,\nmọi lần chụp',
  'onboarding.role.dominant': 'Chủ đạo',
  'onboarding.role.dominantBody': 'Màu mà khung cảnh thực sự được tạo nên từ đó',
  'onboarding.role.support': 'Nền đỡ',
  'onboarding.role.supportBody': 'Thứ giữ nó lại — bề mặt và bóng tối',
  'onboarding.role.signal': 'Tín hiệu',
  'onboarding.role.signalBody': 'Điểm nhấn khiến người ta phải nhìn',
  'onboarding.tune.title': 'Tinh chỉnh từng dải\ntheo cách của bạn',
  'onboarding.tune.body':
    'Chỉnh tông, độ bão hoà và độ sáng mà vẫn giữ liên hệ với khung hình gốc.',
  'onboarding.share.title': 'Giữ lại ảnh.\nChia sẻ tín hiệu.',
  'onboarding.share.body':
    'Mỗi bảng màu đã lưu luôn có hình ảnh, sẵn sàng vào thư viện, bộ màu hoặc thẻ chia sẻ.',
  'onboarding.share.previewName': 'Hoàng hôn bến cảng',
  'onboarding.share.previewMeta': '5 MÀU · SẴN SÀNG CHIA SẺ',
  'onboarding.permission.title': 'Cần camera để đọc ánh sáng',
  'onboarding.permission.body':
    'Khung hình được xử lý trên máy và bị loại bỏ trừ khi bạn lưu. Không có gì được tải lên theo mặc định.',
  'onboarding.permission.reason1': 'Chỉ phân tích màu trên máy',
  'onboarding.permission.reason2': 'Không cần quyền vào thư viện ảnh',
  'onboarding.permission.reason3': 'Thu hồi bất cứ lúc nào trong Cài đặt',
  'onboarding.continue': 'Tiếp tục',
  'onboarding.back': 'Quay lại',
  'onboarding.skip': 'Bỏ qua',
  'onboarding.allowCamera': 'Cho phép camera',
  'onboarding.importInstead': 'Chọn ảnh có sẵn',
  'onboarding.step': 'Bước {current} / {total}',
  'onboarding.saveFailed.title': 'Chưa hoàn tất thiết lập',
  'onboarding.saveFailed.body': 'Thử lại. Lựa chọn của bạn vẫn được giữ.',

  /* --------------------------------------------------------------- B · capture */
  'capture.close': 'Đóng',
  'capture.liveRead': 'ĐANG ĐỌC',
  'capture.reading': 'ĐANG ĐỌC',
  'capture.readFailed': 'KHÔNG ĐỌC ĐƯỢC KHUNG HÌNH',
  'capture.import': 'CHỌN ẢNH',
  'capture.scan': 'QUÉT',
  'capture.shutter': 'Chụp',
  'capture.shutterHint': 'Trích bảng màu từ những gì camera thấy',
  'capture.noDevice': 'MÁY NÀY KHÔNG CÓ CAMERA',
  'capture.cameraNeeded': 'CẦN QUYỀN CAMERA',
  'capture.flash': 'ĐÈN',
  'capture.flash.off': 'TẮT',
  'capture.flash.on': 'BẬT',
  'capture.flash.auto': 'TỰ ĐỘNG',
  'capture.autoWb': 'WB TỰ ĐỘNG',
  'capture.mode.live': 'TRỰC TIẾP',
  'capture.mode.photo': 'ẢNH',
  'capture.mode.scan': 'QUÉT',
  'capture.permission.allowBody': 'Cho phép camera để bắt đầu đọc màu.',
  'capture.permission.deniedBody':
    'Camera đang tắt. Bật lại trong Cài đặt, hoặc chọn một ảnh có sẵn.',
  'capture.notNow': 'Để sau',

  'result.capture': 'ẢNH CHỤP',
  'result.close': 'ĐÓNG',
  'result.retake': 'CHỤP LẠI',
  'result.confidence': 'TIN CẬY {percent}%',
  'result.read': 'ĐỘ ĐỌC {stability}',
  'result.tune': 'Tinh chỉnh',
  'result.save': 'Lưu bảng màu',
  'result.copy': 'CHÉP',
  'result.copyLabel': 'Chép {hex}',
  'result.copyHint': 'Chép {hex} vào clipboard',
  'result.none.title': 'Không có ảnh chụp',
  'result.none.body': 'Ảnh chụp đó đã được lưu hoặc đã bị bỏ.',
  'result.none.action': 'Về thư viện',

  'tune.title': 'Tinh chỉnh dải',
  'tune.cancel': 'Huỷ',
  'tune.apply': 'Áp dụng',
  'tune.before': 'TRƯỚC',
  'tune.after': 'SAU',
  'tune.hue': 'TÔNG',
  'tune.saturation': 'ĐỘ BÃO HOÀ',
  'tune.luminance': 'ĐỘ SÁNG',
  'tune.preset.neutralise': 'TRUNG TÍNH',
  'tune.preset.warm': 'ẤM +5',
  'tune.preset.cinema': 'ĐIỆN ẢNH',
  'tune.preset.reset': 'ĐẶT LẠI',
  'tune.contrast.title': 'Kiểm tra tương phản',
  'tune.contrast.pass': 'ĐẠT',
  'tune.contrast.fail': 'KHÔNG ĐẠT',

  'palette.back': 'QUAY LẠI',
  'palette.more': 'Thêm tuỳ chọn',
  'palette.addTag': 'THẺ',
  'palette.addTag.confirm': 'Thêm thẻ',
  'palette.addTag.placeholder': 'Một từ, viết thường',
  'palette.rename.placeholder': 'Tên bảng màu',
  'palette.menu.rename': 'Đổi tên',
  'palette.menu.pin': 'Ghim lên đầu',
  'palette.menu.unpin': 'Bỏ ghim',
  'palette.menu.duplicate': 'Nhân bản',
  'palette.menu.delete': 'Xoá bảng màu',
  'palette.copyName': '{name} bản sao',
  'palette.delete.title': 'Xoá bảng màu này?',
  'palette.delete.body': '“{name}” sẽ bị xoá khỏi thư viện. Không thể hoàn tác.',
  'palette.delete.confirm': 'Xoá',
  'palette.writeFailed': 'Không lưu được thay đổi',
  'palette.writeFailedDetail': 'Bảng màu giữ nguyên',
  'palette.share': 'Chia sẻ bảng màu',
  'palette.saved': 'lưu {age} trước',
  'palette.colourCount': '{count} màu',
  'palette.loading': 'Đang tải',
  'palette.tools': 'CÔNG CỤ',
  'palette.widgets': 'Widget',

  /* ------------------------------------------------------- C · library, explore */
  'library.title': 'Thư viện',
  'library.meta': '{palettes} bảng màu · {collections} bộ',
  'library.search': 'Tìm trong thư viện',
  'library.filter.all': 'TẤT CẢ',
  'library.filter.recent': 'GẦN ĐÂY',
  'library.filter.pinned': 'ĐÃ GHIM',
  'library.resultCount': '{count} trên {total}',
  'library.empty.title': 'Chưa chụp gì cả',
  'library.empty.body': 'Hướng vào thứ gì có màu. Chỉ mất khoảng hai giây.',
  'library.empty.action': 'Mở camera',
  'library.empty.examples': 'Xem ví dụ',
  'library.monthCount': '{count} lần chụp',
  'library.noResults.title': 'Không có kết quả',
  'library.noResults.body': 'Bộ lọc này chưa có gì. Thử bộ lọc khác, hoặc chụp mới.',
  'library.card.meta': '{count} màu · {age}',
  'library.card.hint': 'Mở bảng màu',

  'hero.label': 'Nổi bật',
  'hero.capture.eyebrow': 'BẮT ĐẦU TỪ ĐÂY',
  'hero.capture.title': 'Đọc ánh sáng ngay trước mặt',
  'hero.capture.body': 'Hướng vào thứ gì có màu. Bảng màu hiện ra sau hai giây.',
  'hero.capture.cta': 'Mở camera',
  'hero.trending.eyebrow': 'TUẦN NÀY',
  'hero.trending.cta': 'Xem ghi chép',
  'hero.studio.eyebrow': 'XƯỞNG GRADIENT',
  'hero.studio.title': 'Biến bảng màu thành bề mặt',
  'hero.studio.body': 'Đưa {name} vào xưởng và xuất thành hình nền.',
  'hero.studio.cta': 'Mở xưởng',

  'explore.title': 'Khám phá',
  'explore.searchPlaceholder': 'Tìm màu, thẻ hoặc mã hex',
  'explore.editorial': 'CHUYÊN ĐỀ · HÀNG TUẦN',
  'explore.inYourLibrary': 'Trong thư viện của bạn',
  'explore.resultCount': 'tìm thấy {count}',
  'explore.noResults': 'Không có kết quả cho “{query}”.',

  /* ---------------------------------------- C1 · băng chuyền trang chính */

  /* -------------------------------- bộ lọc khám phá · thư viện + thịnh hành */
  'filter.toggle': 'BỘ LỌC',
  'filter.active': '{count} BẬT',
  'filter.reset': 'ĐẶT LẠI',
  'filter.expand': 'Hiện bộ lọc màu và phong cách',
  'filter.collapse': 'Ẩn bộ lọc màu và phong cách',
  'filter.group.mood': 'SẮC THÁI MÀU',
  'filter.group.style': 'PHONG CÁCH',
  'filter.group.category': 'TỪ ĐÂU',
  'filter.group.sort': 'THỨ TỰ',
  'library.mood.warm': 'MÀU ẤM',
  'library.mood.cool': 'MÀU LẠNH',
  'library.mood.pastel': 'PASTEL',
  'library.mood.monochrome': 'ĐƠN SẮC',
  'library.mood.vibrant': 'RỰC RỠ',
  'library.style.minimal': 'TỐI GIẢN',
  'library.style.editorial': 'BÁO CHÍ',
  'library.style.retro': 'HOÀI CỔ',
  'library.style.futuristic': 'TƯƠNG LAI',
  'library.style.organic': 'HỮU CƠ',

  /* ---------------------------------------------------- C4 · thịnh hành */
  'trending.title': 'Ghi chép thực địa',
  'trending.meta': '{category} · {age}',
  'trending.homeMeta': 'Ghi chép thực địa, đăng hằng tuần',
  'trending.screenMeta': '{count} bảng màu · tuần này',
  'trending.search': 'Tìm trong ghi chép',
  'trending.seeAll': 'XEM HẾT',
  'trending.back': 'THƯ VIỆN',
  'trending.save': 'LƯU',
  'trending.saved': 'ĐÃ LƯU',
  'trending.resultCount': 'tìm thấy {count}',
  'trending.category.all': 'TẤT CẢ',
  'trending.category.editorial': 'CHUYÊN ĐỀ',
  'trending.category.urban': 'ĐÔ THỊ',
  'trending.category.nature': 'THIÊN NHIÊN',
  'trending.category.interior': 'NỘI THẤT',
  'trending.category.archive': 'LƯU TRỮ',
  'trending.sort.featured': 'NỔI BẬT',
  'trending.sort.new': 'MỚI NHẤT',
  'trending.loading': 'Đang tải ghi chép',
  'trending.loadMore': 'Tải thêm',
  'trending.empty.title': 'Chưa có gì ở đây',
  'trending.empty.body':
    'Chưa bảng màu nào khớp tổ hợp này. Hãy nới một bộ lọc, hoặc đặt lại tất cả.',
  'trending.error.title': 'Không tải được ghi chép',
  'trending.error.body': 'Nguồn dữ liệu không phản hồi. Thư viện của bạn không bị ảnh hưởng.',
  'trending.retry': 'Thử lại',
  'trending.saveFailed': 'Không lưu được',
  'trending.saveFailedDetail': 'Thử lại sau một chút',

  'sets.title': 'Bộ màu',
  'sets.meta': '{count} bộ',
  'sets.empty.title': 'Chưa có bộ nào',
  'sets.empty.body': 'Nhóm các bảng màu thành một bộ để so sánh cạnh nhau và xuất cùng lúc.',
  'sets.empty.action': 'Mở thư viện',
  'sets.create': 'Bộ mới',
  'sets.createFailed': 'Không tạo được bộ',
  'sets.createFailedDetail': 'Chưa có gì được lưu',
  'sets.new.title': 'Bộ mới',
  'sets.new.nameLabel': 'Tên bộ',
  'sets.new.namePlaceholder': 'Đặt tên cho bộ này',
  'sets.new.saving': 'Đang lưu…',
  'sets.new.seeded': 'Bắt đầu với {count} bảng đã ghim',
  'sets.new.seededEmpty': 'Bắt đầu trống',
  'sets.new.startsWith': 'BẮT ĐẦU VỚI',
  'sets.new.hint': 'Chưa ghim bảng nào nên bộ này trống. Thêm bảng màu từ thư viện.',
  'collection.back': 'THƯ VIỆN',
  'collection.edit': 'SỬA',
  'collection.meta.shared': '{count} bảng màu · chia sẻ với {people} người',
  'collection.meta.private': '{count} bảng màu · riêng tư',
  'collection.exportSet': 'XUẤT BỘ',
  'collection.invite': 'MỜI',
  'collection.addedByYou': 'bạn đã thêm',
  'collection.rename': 'ĐỔI TÊN',
  'collection.renamePlaceholder': 'Tên bộ sưu tập',
  'collection.deleteSet': 'XOÁ BỘ',
  'collection.delete.title': 'Xoá bộ này?',
  'collection.delete.body': '“{name}” sẽ bị xoá. Các bảng màu bên trong vẫn được giữ.',
  'collection.removePalette': 'Bỏ {name} khỏi bộ này',
  'collection.inviteCopied': 'Đã chép liên kết. Nó mở bộ này trên máy đã có sẵn bộ đó.',
  'collection.system': 'HỆ MÀU',
  'collection.system.meta': 'Gộp từ {count} bảng màu',
  'collection.system.empty': 'Thêm bảng màu và bộ này sẽ dựng một hệ màu từ tất cả.',
  'collection.pairings': 'CẶP MÀU',
  'collection.pairingSample': 'Aa',
  'collection.pairingRatio': '{ratio}:1',
  'collection.pairingLabel': '{hex} trên {background}, tỉ lệ {ratio} trên 1',
  'collection.gap.missing-signal': 'Chưa màu nào đủ rực để làm điểm nhấn.',
  'collection.gap.narrow-lightness': 'Mọi màu cùng một độ sáng, nên không tạo được tương phản.',
  'collection.gap.no-safe-pairing': 'Không cặp màu nào ở đây đặt chữ lên nhau được.',
  'collection.gap.action': 'Chụp thêm',
  'collection.gap.none': 'Bộ này đã đủ thành một hệ màu.',
  'collection.members': 'TRONG BỘ NÀY',
  'sets.openGaps': 'thiếu {count}',
  'sets.complete': 'Đủ',

  'share.title': 'Chia sẻ “{name}”',
  'share.format.1x1': '1:1 BÀI ĐĂNG',
  'share.format.4x5': '4:5 DÒNG TIN',
  'share.format.9x16': '9:16 STORY',
  'share.includePhoto': 'Kèm ảnh',
  'share.showHex': 'Hiện mã hex',
  'share.removeWatermark': 'Bỏ watermark',
  'share.saveImage': 'Lưu ảnh',
  'share.share': 'Chia sẻ…',

  /* ------------------------------------------------------------ D · pro, account */
  'paywall.close': 'Đóng',
  'paywall.title': 'Mở trọn\nbộ ba dải',
  'paywall.body': 'Dải thứ ba, chụp không giới hạn, và xuất ra đúng định dạng công cụ bạn dùng.',
  'paywall.benefit1': 'Bảng màu & bộ màu không giới hạn',
  'paywall.benefit2': 'Gộp bộ, xuất ASE / JSON / P3',
  'paywall.benefit3': 'Thẻ chia sẻ không watermark',
  'paywall.monthly': 'HÀNG THÁNG',
  'paywall.yearly': 'HÀNG NĂM',
  'paywall.perMonth': 'MỖI THÁNG',
  'paywall.perMonthEquivalent': '{price} / THÁNG',
  'paywall.save': 'TIẾT KIỆM 40%',
  'paywall.cta': 'Dùng thử 7 ngày',
  'paywall.restore': 'PHỤC HỒI',
  'paywall.restoreNone': 'Không tìm thấy giao dịch trước đó trên Apple ID này.',
  'paywall.terms': 'ĐIỀU KHOẢN',
  'paywall.privacy': 'BẢO MẬT',
  'paywall.smallPrintYearly':
    'Sau đó {price}/năm. Huỷ bất cứ lúc nào trên App Store; bảng màu đã lưu vẫn là của bạn.',
  'paywall.smallPrintMonthly':
    'Sau đó {price}/tháng. Huỷ bất cứ lúc nào trên App Store; bảng màu đã lưu vẫn là của bạn.',

  'you.title': 'Bạn',
  'you.meta': 'Thư viện cục bộ · máy này',
  'you.signature.eyebrow': 'DẤU MÀU CỦA BẠN',
  'you.signature.body': 'Dựng từ mọi lần chụp bạn đã giữ lại.',
  'you.signature.empty': 'Chụp một tấm và phần này tự dựng lên.',
  'you.signature.label': 'Dấu màu của bạn',
  'you.stat.palettes': 'BẢNG MÀU',
  'you.stat.pinned': 'ĐÃ GHIM',
  'you.stat.colours': 'MÀU',
  'you.stat.collections': 'BỘ',
  'you.stat.thisMonth': 'THÁNG NÀY',
  'you.stat.hint': 'Mở thư viện',
  'you.taste.title': 'Thứ bạn hay giữ',
  'you.taste.meta': 'Đọc từ chính các lần chụp của bạn, không phải khảo sát',
  'you.taste.empty': 'Chụp thêm vài tấm là phần này hiện ra.',
  'you.taste.count': '{count} bảng màu',
  'you.taste.hint': 'Lọc thư viện theo mục này',
  'you.collections.title': 'Bộ sưu tập',
  'you.collections.empty': 'Gom bảng màu vào một bộ để so sánh và xuất cùng nhau.',
  'you.collections.count': '{count} bảng màu',
  'you.recent.title': 'Chụp gần đây',
  'you.recent.empty': 'Các lần chụp sẽ hiện ở đây.',
  'you.controls.title': 'Điều khiển',
  'you.controls.meta': 'Chụp, màu sắc và thiết bị này',
  'you.more.title': 'Khác',
  'you.seeAll': 'XEM HẾT',
  'you.newSet': 'Tạo bộ mới',
  'you.appearance': 'Giao diện',
  'you.appearance.chroma': 'CHROMA',
  'you.appearance.swiss': 'SWISS',
  'you.colourSpace': 'Không gian màu',
  'you.defaultExport': 'Xuất mặc định',
  'you.haptics': 'Rung khi chụp',
  'you.sound': 'Âm thanh',
  'you.backdrop': 'Nền chuyển động',
  'you.reminder': 'Nhắc hằng ngày',
  'you.language': 'Ngôn ngữ',
  'you.languageSwitch': 'Chuyển giữa tiếng Anh và tiếng Việt',
  'you.open': 'MỞ',
  'you.unread': '{count} MỚI',
  'you.version': 'V{version} · BẢO MẬT · HỖ TRỢ',

  /* --------------------------------------------------------------- G · deeper */
  'scan.exit': 'THOÁT',
  'scan.pinned': 'ĐÃ GHIM {count}',
  'scan.pinnedWhileWalking': 'GHIM TRONG KHI DI CHUYỂN',
  'scan.now': 'HIỆN TẠI {hex}',
  'scan.build': 'Tạo bảng màu từ {count} ghim',
  'scan.pinLabel': 'Ghim một màu',
  'scan.pinHint': 'Ghim màu ở giữa khung ngắm',
  'scan.removePin': 'Bỏ {hex}',
  'scan.liveScene': 'KHUNG CẢNH TRỰC TIẾP',

  'import.title': 'Chọn điểm',
  'import.cancel': 'Huỷ',
  'import.extract': 'Trích',
  'import.photo': 'ẢNH ĐÃ CHỌN',
  'import.decoding': 'ĐANG GIẢI MÃ',
  'import.reading': 'ĐANG ĐỌC TOÀN ẢNH',
  'import.autoRead': 'TÌM THẤY {count} MÀU · CHẠM ĐỂ CHỈNH',
  'import.failed': 'KHÔNG ĐỌC ĐƯỢC ẢNH NÀY',
  'import.points': 'CHỤM ĐỂ ZOOM · {count}/{max} ĐIỂM',
  'import.radius': 'BÁN KÍNH LẤY MẪU',
  'import.radiusValue': '{px} PX · TRUNG BÌNH',
  'import.mode.manual': 'THỦ CÔNG',
  'import.mode.auto': 'TỰ ĐỘNG',
  'import.mode.edges': 'BIÊN',
  'import.choosePhoto': 'CHỌN ẢNH',
  'import.changePhoto': 'ĐỔI ẢNH',
  'import.removePoint': 'Bỏ {hex}',
  'import.hint': 'Chạm vào ảnh để thêm ít nhất hai điểm lấy mẫu. Chạm một điểm để bỏ nó.',
  'import.tapLabel': 'Ảnh, chạm để lấy mẫu',
  'import.tapHint': 'Thêm một điểm lấy mẫu',
  'import.cinematic': 'Làm điện ảnh',

  'compare.title': 'So sánh',
  'compare.meta': '2 bảng màu · ma trận ΔE',
  'compare.matrixLabel': 'KHOẢNG CÁCH THỊ GIÁC ΔE00',
  'compare.closest': 'Cặp gần nhất',
  'compare.swap': 'ĐỔI',
  'compare.temperature': 'Nhiệt màu',
  'compare.tempCool': 'lạnh 4200K',
  'compare.tempWarm': 'ấm 2700K',
  'compare.addThird': 'Thêm thứ ba',
  'compare.choose': 'So với bảng màu',
  'compare.swapSides': 'Đổi chỗ A và B',
  'compare.mergedName': '{first} × {second}',
  'compare.merge': 'Gộp thành bộ',
  'compare.needTwo': 'So sánh cần hai bảng màu đã lưu.',
  'compare.cellLabel': '{from} tới {to}, delta E {value}',

  'contrast.title': 'Kiểm tra tương phản',
  'contrast.meta': '{name} · WCAG 2.2',
  'contrast.largeSample': 'Mẫu chữ lớn',
  'contrast.largeBody': 'Chữ nội dung 14px trên dải chủ đạo.',
  'contrast.signalOnInk': 'Tín hiệu trên nền mực',
  'contrast.signalBody': 'Chữ nội dung 14px trên nền mực.',
  'contrast.onDominant': 'TRÊN CHỦ ĐẠO',
  'contrast.onSurface': 'TRÊN NỀN',
  'contrast.onPaper': 'TRÊN GIẤY',
  'contrast.suggestedFix': 'ĐỀ XUẤT SỬA',
  'contrast.applyFix': 'Áp dụng đề xuất',
  'contrast.fixNote': 'Độ sáng {delta}, giữ tông',
  'contrast.simulationNote': 'Mô phỏng {name} chỉ để xem trước — kết luận ở trên dùng độ sáng thật',

  'gradient.title': 'Xưởng gradient',
  'gradient.close': 'Đóng',
  'gradient.save': 'Lưu',
  'gradient.angle': 'GÓC',
  'gradient.interpolation': 'NỘI SUY',
  'gradient.grain': 'Thêm hạt phim',
  'gradient.wallpaper': 'HÌNH NỀN',
  'gradient.exportFailed': 'Không xuất được',
  'gradient.exportFailedDetail': 'Không dựng được tệp từ dải màu này',

  'theme.title': 'Xem khi áp dụng',
  'theme.meta': '{name} dạng UI',
  'theme.dashboard': 'Bảng điều khiển',
  'theme.uptime': 'HOẠT ĐỘNG',
  'theme.sessions': 'PHIÊN',
  'theme.alerts': 'CẢNH BÁO',
  'theme.primaryAction': 'Hành động chính',
  'theme.webHeadline': 'Màu sắc có sức nặng',
  'theme.posterTitle': 'GHI CHÉP\nHIỆN TRƯỜNG',
  'theme.posterMeta': 'TRIỂN LÃM · SỐ 04',
  'theme.slideEyebrow': 'TỔNG KẾT QUÝ',
  'theme.slideTitle': 'Ánh sáng đã nói gì',
  'theme.roleMapping': 'GÁN VAI TRÒ · TỰ ĐỘNG',
  'theme.export': 'Xuất giao diện',
  'theme.unreadable': 'CHỮ TRÊN NỀN KHÔNG ĐẠT AA — TINH CHỈNH TRƯỚC KHI XUẤT',

  'export.title': 'Xuất',
  'export.close': 'Đóng',
  'export.copy': 'Chép',
  'export.includeTints': 'Kèm màu nhạt & đậm',
  'export.p3': 'Dự phòng Display P3',
  'export.semanticNames': 'Tên vai trò ngữ nghĩa',
  'export.sendTo': 'GỬI TỚI',
  'export.figma': 'Thư viện Figma',
  'export.gist': 'GitHub gist',
  'export.copyToClipboard': 'Chép vào clipboard',
  'export.openFailed': 'Không mở được đích đến',
  'export.openFailedDetail': 'Mã đã nằm trong clipboard',

  'widgets.close': 'XONG',

  'activity.title': 'Hoạt động',
  'activity.allRead': 'ĐÃ ĐỌC HẾT',
  'activity.captured': 'CHỤP {age} TRƯỚC',
  'activity.markRead': 'ĐÁNH DẤU ĐÃ ĐỌC',
  'activity.none.title': 'Chưa có hoạt động chung',
  'activity.none.body':
    'Chia sẻ bộ màu và theo dõi người khác cần có tài khoản. Ảnh chụp của bạn đều ở phần tổng kết dưới đây.',
  'activity.thisMonth': 'THÁNG NÀY',
  'activity.recap': 'Năm màu sắc của bạn',
  'activity.recapEmpty': 'Tháng này chưa chụp gì.',
  'activity.recapSummary': 'Bạn đã chụp {count} bảng màu. {leader} đang dẫn — {runnerUp} đang bám.',
  'activity.recapSummaryOne': 'Bạn đã chụp 1 bảng màu.',
  'activity.barLabel': '{label}, {count} bảng màu',

  /* ---------------------------------------------------------------- E · states */
  'state.loading': 'Đang tải',
  'state.offline.title': 'Bạn đang offline',
  'state.offline.body': 'Vẫn chụp được — việc trích màu chạy trên máy. Đồng bộ sẽ tự tiếp tục.',
  'state.nothing.title': 'Không có gì ở đây',
  'state.nothing.body': 'Màn hình đó đã chuyển đi hoặc chưa từng tồn tại.',
  'state.nothing.action': 'Về thư viện',
  'state.tool.title': 'Chưa có gì để làm',
  'state.tool.body': 'Hãy chụp một bảng màu trước, rồi mở mục này từ trang chi tiết.',
  'state.tool.action': 'Mở thư viện',
  'toast.saved': 'Đã lưu bảng màu',
  'toast.undo': 'HOÀN TÁC',

  /* ------------------------------------------------------------------- shared */
  'common.pro': 'PRO',
  'common.cancel': 'Huỷ',
  'common.save': 'Lưu',
  'common.done': 'XONG',
  'common.working': 'ĐANG XỬ LÝ',
  'common.selected': 'Đã chọn',
  'common.css': 'CSS',
  'common.svg': 'SVG',
  'common.ase': 'ASE',
  'common.json': 'JSON',
  'common.proJson': 'PRO · JSON',
  'common.stability.stable': 'ổn định',
  'common.stability.drifting': 'đang lệch',
  'common.stability.unstable': 'không ổn',

  /* --------------------------------------------------------------- M · music */
  'memory.music': 'ÂM NHẠC',
  'memory.unpaired': 'Chưa có nhạc. Tìm một bản hợp với khoảnh khắc này.',
  'memory.findMusic': 'Tìm nhạc',
  'memory.replaceTrack': 'Đổi bản nhạc',
  'memory.trackUnavailable': 'Không khả dụng',
  'pair.stage.colour': 'ĐANG ĐỌC MÀU',
  'pair.stage.atmosphere': 'ĐANG ĐỌC KHÔNG KHÍ',
  'pair.stage.music': 'ĐANG TÌM NHẠC',
  'pair.stage.previews': 'ĐANG CHUẨN BỊ',
  'pair.title': 'Nhạc cho khoảnh khắc này',
  'pair.subtitle': 'Gợi ý dựa trên màu sắc, ánh sáng và không khí của ảnh.',
  'pair.why': 'Vì sao hợp',
  'pair.hear': 'Nghe thử',
  'pair.pause': 'Tạm dừng',
  'pair.loading': 'Đang tải',
  'pair.previewLength': 'Nghe thử 0:30',
  'pair.noPreview': 'Không có đoạn nghe thử',
  'pair.choose': 'Chọn bản này',
  'pair.chosen': 'Đã chọn',
  'pair.reject': 'Bỏ qua bản này',
  'pair.again': 'Tìm lại',
  'pair.skip': 'Chỉ lưu màu',
  'pair.openIn': 'Nghe trên Apple Music',
  'pair.position': '{current} trên {total}',
  'pair.mood.serene': 'tĩnh lặng',
  'pair.mood.tender': 'dịu dàng',
  'pair.mood.luminous': 'rực sáng',
  'pair.mood.vivid': 'rực rỡ',
  'pair.mood.nocturnal': 'về đêm',
  'pair.mood.melancholy': 'trầm buồn',
  'pair.mood.earthy': 'mộc mạc',
  'pair.mood.stark': 'gắt gao',
  'pair.reason.warmth': 'độ ấm',
  'pair.reason.energy': 'năng lượng',
  'pair.reason.luminosity': 'ánh sáng',
  'pair.reason.pace': 'nhịp',
  'pair.reason.texture': 'chất',
  'pair.reason.genre': 'thể loại',
  'pair.reason.era': 'thời kỳ',
  'pair.reason.mood': 'tâm trạng',
  'pair.reason.contrast': 'tương phản',
  'pair.becauseGenre':
    '{genre}, vì bảng màu {mood} — ánh sáng {light}, tông {temperature} — gợi đến điều gì đó {pace}.',
  'pair.because':
    'Bảng màu {mood} — ánh sáng {light}, tông {temperature} — gợi đến điều gì đó {pace}.',
  'pair.light.low': 'dịu',
  'pair.light.even': 'đều',
  'pair.light.bright': 'sáng',
  'pair.temperature.warm': 'ấm',
  'pair.temperature.cool': 'lạnh',
  'pair.temperature.neutral': 'trung tính',
  'pair.pace.slow': 'thong thả',
  'pair.pace.medium': 'đều đặn',
  'pair.pace.fast': 'chuyển động',
  'pair.error.offline': 'Bạn đang ngoại tuyến. Hãy lưu màu và ghép nhạc sau.',
  'pair.error.provider': 'Không kết nối được kho nhạc.',
  'pair.error.empty': 'Chưa có bản nào hợp bảng màu này. Thử tìm lại để có gợi ý khác.',
  'pair.error.notConfigured': 'Bản dựng này chưa hỗ trợ ghép nhạc.',
  'pair.empty': 'Chưa có bản nào.',

  'grade.title': 'Chỉnh màu',
  'grade.subtitle': 'Đọc từ chính ảnh này, ngay trên máy',
  'grade.auto': 'Tự động',
  'grade.original': 'Ảnh gốc',
  'grade.stocks': 'Chất phim',
  'grade.controls': 'Tinh chỉnh',
  'grade.apply': 'Áp dụng',
  'grade.applied': 'Đã lưu chỉnh màu',
  'grade.remove': 'Bỏ chỉnh màu',
  'grade.compare': 'Giữ để so sánh',
  'grade.noPhoto': 'Bảng màu này không có ảnh để chỉnh.',
  'grade.loading': 'Đang mở ảnh',
  'grade.failed': 'Không mở được ảnh này.',
  'grade.failedDetail': 'Tệp có thể đã bị di chuyển hoặc bị hệ thống xoá.',
  'grade.proBody':
    'Chất phim và tinh chỉnh từng tham số thuộc gói Pro. Chỉnh màu tự động luôn miễn phí.',
  'grade.exposure': 'Phơi sáng',
  'grade.contrast': 'Tương phản',
  'grade.lift': 'Nâng đen',
  'grade.saturation': 'Độ bão hoà',
  'grade.temperature': 'Nhiệt màu',
  'grade.tint': 'Sắc lệch',
  'grade.vignette': 'Tối viền',
  'grade.grain': 'Hạt phim',
  'grade.stops': '{value} khẩu',
  'grade.amount': '{value} phần trăm',
  'grade.save': 'Lưu ảnh',
  'grade.share': 'Chia sẻ',
  'grade.exporting': 'Đang kết xuất…',
  'grade.savedPhoto': 'Đã lưu vào Ảnh',
  'grade.sharedPhoto': 'Đã chia sẻ',
  'grade.saveDenied': 'Chroma Wave không thêm được vào Ảnh.',
  'grade.saveDeniedDetail': 'Cho phép truy cập Ảnh trong Cài đặt để lưu ảnh đã chỉnh màu.',
  'grade.exportFailed': 'Không xuất được ảnh này.',
  'grade.exportFailedDetail': 'Tệp có thể đã bị di chuyển, hoặc lớn hơn mức máy này kết xuất được.',

  'living.title': 'Ký ức sống',
  'living.play': 'Phát',
  'living.pause': 'Tạm dừng',
  'living.replay': 'Phát lại',
  'living.close': 'Đóng',
  'living.silent': 'Chưa ghép nhạc — đang phát không tiếng',
  'living.pair': 'Ghép nhạc',
  'living.noPhoto': 'Ký ức sống cần có ảnh.',
  'living.scene.frame': 'Khung hình',
  'living.scene.title': 'Ở đâu và khi nào',
  'living.scene.palette': 'Những màu',
  'living.scene.atmosphere': 'Cảm giác lúc đó',
  'living.scene.track': 'Bản nhạc',
  'living.export': 'Xuất video cần một encoder mà bản dựng này chưa có.',

  'atmosphere.mood.serene': 'Tĩnh lặng',
  'atmosphere.mood.tender': 'Dịu dàng',
  'atmosphere.mood.luminous': 'Rực sáng',
  'atmosphere.mood.vivid': 'Sống động',
  'atmosphere.mood.nocturnal': 'Về đêm',
  'atmosphere.mood.melancholy': 'U hoài',
  'atmosphere.mood.earthy': 'Mộc mạc',
  'atmosphere.mood.stark': 'Khắc khổ',

  'rewind.title': 'Nhìn lại',
  'rewind.subtitle': 'Điều thư viện của bạn cứ quay về',
  'rewind.onThisDay': 'Ngày này năm xưa',
  'rewind.onThisDay.meta': '{count} từ những năm trước',
  'rewind.collections': 'Tự hình thành',
  'rewind.recaps': 'Nhìn lại theo kỳ',
  'rewind.dna': 'Gu của bạn',
  'rewind.dna.warm': 'Nghiêng về ấm',
  'rewind.dna.cool': 'Nghiêng về lạnh',
  'rewind.dna.neutral': 'Ở khoảng giữa',
  'rewind.dna.paired': '{percent} phần trăm đã có nhạc',
  'rewind.dna.memories': 'Đọc từ {count} ký ức',
  'rewind.empty': 'Chụp thêm vài tấm nữa là phần này tự đầy lên.',
  'rewind.failed': 'Không đọc được thư viện của bạn.',
  'rewind.retry': 'Thử lại',
  'rewind.recap.month': '{key} · {count} ký ức',
  'rewind.recap.year': '{key} · {count} ký ức',
  'rewind.collection.month': '{key} của bạn',
  'rewind.collection.mood': '{key}',
  'rewind.collection.colour': 'Màu này',
  'rewind.collection.artist': '{key}',
  'rewind.collection.genre': '{key}',
  'rewind.count': '{count}',
  'grade.applying': 'Đang áp dụng…',

  'studio.title': 'Studio',
  'studio.subtitle': 'Ánh sáng ở ống kính, màu ở khung hình',
  'studio.shutter': 'Chụp',
  'studio.retake': 'Chụp lại',
  'studio.keep': 'Giữ',
  'studio.exposure': 'Phơi sáng',
  'studio.zoom': 'Thu phóng',
  'studio.torch': 'Đèn',
  'studio.focusHint': 'Chạm vào preview để lấy nét và đo sáng ở đó',
  'studio.preparing': 'Đang khởi động camera',
  'studio.reading': 'Đang đọc khung hình',
  'studio.failed': 'Không đọc được khung hình này.',
  'studio.looks': 'Chất ảnh',
  'studio.liveNote': 'Màu được áp lên khung bạn chụp, không phải lên preview.',
  'studio.stops': '{value} khẩu',
  'studio.times': '{value}×',
  'studio.mode': 'STUDIO',
};
